// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class monsterTypeReferenceTable
{
    private static monsterTypeReferenceTable instance;
    public static monsterTypeReferenceTable Instance
    {
        get
        {
            if (instance == null)
                instance = new monsterTypeReferenceTable();
            return instance;
        }
    }

	public class Row
	{
		public string RECORD_ID;
		public string MONSTER_TYPE_CODE;
		public string MONSTER_TYPE_NAME;
	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}
    
    public void loadLocalMonsterTypeReference()
    {
        TextAsset monsterTypeReferenceFile = Resources.Load("Account/mst_monster_type") as TextAsset;
        Load(monsterTypeReferenceFile);
    }

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.RECORD_ID = grid[i][0];
			row.MONSTER_TYPE_CODE = grid[i][1];
			row.MONSTER_TYPE_NAME = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_RECORD_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
	public Row Find_MONSTER_TYPE_CODE(string find)
	{
		return rowList.Find(x => x.MONSTER_TYPE_CODE == find);
	}
	public List<Row> FindAll_MONSTER_TYPE_CODE(string find)
	{
		return rowList.FindAll(x => x.MONSTER_TYPE_CODE == find);
	}
	public Row Find_MONSTER_TYPE_NAME(string find)
	{
		return rowList.Find(x => x.MONSTER_TYPE_NAME == find);
	}
	public List<Row> FindAll_MONSTER_TYPE_NAME(string find)
	{
		return rowList.FindAll(x => x.MONSTER_TYPE_NAME == find);
	}

}