// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using System.Text;
using Skill;

public class SkillConfigTable
{
    static SkillConfigTable instance;
    public static SkillConfigTable Instance
    {
        get
        {
            if (instance == null)
            {
                instance = new SkillConfigTable();
            }
            return instance;
        }
    }
    public IDictionary<string, SkillConfig> SkillConfigDicForReference = new Dictionary<string, SkillConfig>();
    
	public class Row
	{
		public string RECORD_ID;
        public string REAL_NAME;
		public string USEABLE_MONSTER_TYPE;
		public string ATTACK_WEIGHT;
		public string ATTACK_TYPE;
        public string SP_LEVEL;
		public string TRIGGER_DIS_MIN;
        public string TRIGGER_DIS_MAX;
        public string CAN_LEVELUP;
        public string RARITY_LEVEL;
    }

	public List<Row> rowList = new List<Row>();
	bool isLoaded;

	public bool IsLoaded()
	{
		return isLoaded;
	}
    
    public IEnumerator LoadAllSkillConfigs()
    {
        switch (ResourceLoadingSetting.ConfigFileLoadingMode)
        {
            case ResourceLoadMode.CachAB:
                break;
            case ResourceLoadMode.StreamingAssetAB:
                break;
            case ResourceLoadMode.Resource:
                LoadAllSkillConfigFromLocalConfigFile();
                break;
        }
        RefreshSkillConfigDicForReference();
        yield break;
    }
    
    public static void RefreshSkillConfigDicForReference()
    {
        IDictionary<string, SkillConfig> Dic = new Dictionary<string, SkillConfig>();
        List<SkillConfig> ALL = Instance.RowsToSkillConfigList(Instance.rowList);
        foreach (SkillConfig keyValuePair in ALL)
        {
            if (!Dic.ContainsKey(keyValuePair.RECORD_ID))
            {
                Dic.Add(new KeyValuePair<string, SkillConfig>(keyValuePair.RECORD_ID, keyValuePair));
                //Debug.Log("以下技能加入字典： RECORDID:"+keyValuePair.RECORD_ID + "  realname:"+ keyValuePair.REAL_NAME);
            }
            else
                Debug.Log("致命错误「技能配置文件」技能ID重复："+ keyValuePair .RECORD_ID);
        }
        Instance.SkillConfigDicForReference = Dic;
    }
    
    public static SkillConfig GetSkillConfigByID(string ID)
    {
        if (ID != null)
        {
            Instance.SkillConfigDicForReference.TryGetValue(ID, out SkillConfig skillConfig);
            return skillConfig;
        }else{
            return null;
        }
    }
    
    public static List<SkillConfig> GetSkillConfigsOfType(string type)
    {
        List<SkillConfig> SkillConfigsOfType = new List<SkillConfig>();
        foreach (KeyValuePair<string, SkillConfig> one in Instance.SkillConfigDicForReference)
        {
            if (one.Value.TYPE == type)
                SkillConfigsOfType.Add(one.Value);
        }
        return SkillConfigsOfType;
    }
    
    public static IDictionary<string,string> GetSkillIDAndNameDic(string type, bool[] ranges, int rarelevel)// close, near, far.rarelevel = -1代表全部，0代表无星级技能
    {
        Dictionary<string, string> SkillIDAndNameDic = new Dictionary<string, string>
        {
            { "-1", "空" }
        };
        List<SkillConfig> list = GetSkillConfigsOfType(type);
        foreach (SkillConfig one in list)
        {    
            if (RangeLimit(one.AI_MIN_DIS, one.AI_MAX_DIS, ranges[0], ranges[1], ranges[2],ranges[3]) && (one.RARITY_LEVEL == rarelevel || rarelevel == -1))
            {
                SkillIDAndNameDic.Add(one.RECORD_ID, one.REAL_NAME);
            }
        }
        return SkillIDAndNameDic;
    }
        
    public static bool RangeLimit(float dis_min ,float dis_max, bool close, bool near, bool far, bool outrange) // 待修 
    {
        if (dis_max > dis_min)
        {
            if ((dis_min <= 5 && dis_max >= 0f) && close)
            {
                return true;
            }
            if ((dis_min <= 10f && dis_max >= 5f) && near)
            {
                return true;
            }
            if ((dis_min <= 15f && dis_max >= 10f) && far)
            {
                return true;
            }
            if ((dis_min <= 20f && dis_max >= 15f) && outrange)
            {
                return true;
            }
        }
        return false;
    }
    
    public static void LoadAllSkillConfigFromLocalConfigFile()//1
    {
        if (Application.platform == RuntimePlatform.OSXEditor || Application.platform == RuntimePlatform.WindowsEditor
            ||
            Application.platform == RuntimePlatform.WindowsPlayer || Application.platform == RuntimePlatform.OSXPlayer)
        {
            TextAsset csv = Resources.Load("Account/mst_skill") as TextAsset;
            if (csv != null)
            {
                Instance.Load(csv);
            }
        }
        else if (Application.platform == RuntimePlatform.Android || Application.platform == RuntimePlatform.IPhonePlayer)
        {
            TextAsset csv = Resources.Load("Account/mst_skill") as TextAsset;//未定，这个瞎写的。
            if (csv != null)
            {
                Instance.Load(csv);
            }
        }
    }

	public List<Row> GetRowList()
	{
		return rowList;
	}

    public void SaveByCurrentRows(string filePath)
    {
        List<Row> toDeleteList = new List<Row>();
        foreach(Row row in rowList)
        {
            if (row.REAL_NAME == null)
                toDeleteList.Add(row);
        }
        foreach(Row row in toDeleteList)
        {
            Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
            rowList.Remove(row);
        }

        string[][] grid = new string[rowList.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[12];
            if (i == 0)
            {
                grid[i][0] = "RECORD_ID";
                grid[i][1] = "REAL_NAME";
                grid[i][2] = "USEABLE_MONSTER_TYPE";
                grid[i][3] = "ATTACK_WEIGHT";
                grid[i][4] = "ATTACK_TYPE";
                grid[i][5] = "SP_LEVEL";
                grid[i][6] = "TRIGGER_DIS_MIN";
                grid[i][7] = "TRIGGER_DIS_MAX";
                grid[i][8] = "CAN_LEVELUP";
                grid[i][9] = "RARITY_LEVEL";
            }
            else
            {
                grid[i][0] = rowList[i - 1].RECORD_ID;
                grid[i][1] = rowList[i - 1].REAL_NAME;
                grid[i][2] = rowList[i - 1].USEABLE_MONSTER_TYPE;
                grid[i][3] = rowList[i - 1].ATTACK_WEIGHT;
                grid[i][4] = rowList[i - 1].ATTACK_TYPE;
                grid[i][5] = rowList[i - 1].SP_LEVEL;
                grid[i][6] = rowList[i - 1].TRIGGER_DIS_MIN;
                grid[i][7] = rowList[i - 1].TRIGGER_DIS_MAX;
                grid[i][8] = rowList[i - 1].CAN_LEVELUP;
                grid[i][9] = rowList[i - 1].RARITY_LEVEL;
            }
        }
        string delimiter = ",";
        StringBuilder sb = new StringBuilder();

        for (int index = 0; index < grid.Length; index++)
            sb.AppendLine(string.Join(delimiter, grid[index]));

        Debug.Log("尝试最终保存文件" + filePath);
        StreamWriter outStream = System.IO.File.CreateText(filePath);
        outStream.WriteLine(sb);
        outStream.Close();
    }
    
	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
        try
        {
            for (int i = 1; i < grid.Length; i++)
            {
                if (grid[i].Length < 10)
                    continue;
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    REAL_NAME = grid[i][1],
                    USEABLE_MONSTER_TYPE = grid[i][2],
                    ATTACK_WEIGHT = grid[i][3],
                    ATTACK_TYPE = grid[i][4],
                    SP_LEVEL = grid[i][5],
                    TRIGGER_DIS_MIN = grid[i][6],
                    TRIGGER_DIS_MAX = grid[i][7],
                    CAN_LEVELUP = grid[i][8],
                    RARITY_LEVEL = grid[i][9]
                };
                rowList.Add(row);
            }
            isLoaded = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
    }

    public List<SkillConfig> RowsToSkillConfigList(List<Row> Rows)
    {
        List<SkillConfig> skillConfigs = new List<SkillConfig>();
        foreach(Row row in Rows)
        {
            SkillConfig newConfig = RowToSkillConfig(row);
            if (newConfig != null)
                skillConfigs.Add(newConfig);
        }
        return skillConfigs;
    }

    public Row SkillConfigToRow(SkillConfig skillConfig)
    {
        if (skillConfig == null)
            return null;
        Row row = new Row
        {
            RECORD_ID = skillConfig.RECORD_ID,
            USEABLE_MONSTER_TYPE = skillConfig.TYPE,
            REAL_NAME = skillConfig.REAL_NAME,
            ATTACK_WEIGHT = skillConfig.ATTACK_WEIGHT.ToString()
        };

        switch (skillConfig.STATE_TYPE)
        {
            case BehaviorType.GR:
                row.ATTACK_TYPE = "GR";
                break;
            case BehaviorType.GI:
                row.ATTACK_TYPE = "GI";
                break;
            case BehaviorType.GM:
                row.ATTACK_TYPE = "GM";
                break;
            case BehaviorType.CT:
                row.ATTACK_TYPE = "CT";
                break;
            case BehaviorType.NONE:
                row.ATTACK_TYPE = "NONE";
                break;
        }
        
        row.TRIGGER_DIS_MIN = skillConfig.AI_MIN_DIS.ToString();
        row.TRIGGER_DIS_MAX = skillConfig.AI_MAX_DIS.ToString();
                
        switch (skillConfig.SP_LEVEL)
        {
            case 0:
                row.SP_LEVEL = "0";
                break;
            case 1:
                row.SP_LEVEL = "1";
                break;
            case 2:
                row.SP_LEVEL = "2";
                break;
            case 3:
                row.SP_LEVEL = "3";
                break;
            default:
                row.SP_LEVEL = "-1";
                break;
        }
        row.CAN_LEVELUP = skillConfig.CAN_LEVELUP;
        row.RARITY_LEVEL = skillConfig.RARITY_LEVEL.ToString();
        return row;
    }

    public SkillConfig RowToSkillConfig(Row row)
    {
        SkillConfig _SkillConfig = new SkillConfig
        {
            TYPE = row.USEABLE_MONSTER_TYPE,
            RECORD_ID = row.RECORD_ID,
            REAL_NAME = row.REAL_NAME,
            ATTACK_WEIGHT = float.Parse(row.ATTACK_WEIGHT)
        };

        switch (row.ATTACK_TYPE)
        {
            case "GR":
                _SkillConfig.STATE_TYPE = BehaviorType.GR;
                break;
            case "GI":
                _SkillConfig.STATE_TYPE = BehaviorType.GI;
                break;
            case "GM":
                _SkillConfig.STATE_TYPE = BehaviorType.GM;
                break;
            case "CT":
                _SkillConfig.STATE_TYPE = BehaviorType.CT;
                break;
            case "NONE":
                _SkillConfig.STATE_TYPE = BehaviorType.NONE;
                break;
            default:
                _SkillConfig.STATE_TYPE = BehaviorType.NONE;
                break;
        }

        _SkillConfig.AI_MIN_DIS = float.Parse(row.TRIGGER_DIS_MIN);
        _SkillConfig.AI_MAX_DIS = float.Parse(row.TRIGGER_DIS_MAX);

        switch(row.SP_LEVEL)
        {
            case "0":
                _SkillConfig.SP_LEVEL = 0;
                break;
            case "1":
                _SkillConfig.SP_LEVEL = 1;
                break;
            case "2":
                _SkillConfig.SP_LEVEL = 2;
                break;
            case "3":
                _SkillConfig.SP_LEVEL = 3;
                break;
            default:
                _SkillConfig.SP_LEVEL = -1;
                break;
        }
        _SkillConfig.CAN_LEVELUP = row.CAN_LEVELUP;
        _SkillConfig.RARITY_LEVEL = int.Parse(row.RARITY_LEVEL);
        return _SkillConfig;
    }

    public List<Row> FindAll_type_keyName(string type, string keyName)
    {
        return (rowList.FindAll(x => x.REAL_NAME == keyName).Intersect(rowList.FindAll(x => x.USEABLE_MONSTER_TYPE == type))).ToList();
    }

    public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
        return rowList.Count <= i ? null : rowList[i];
    }

    public Row Find_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}    
	public Row Find_MONSTER_TYPE_CODE(string find)
	{
		return rowList.Find(x => x.USEABLE_MONSTER_TYPE == find);
	}
	public List<Row> FindAll_MONSTER_TYPE(string find)
	{
		return rowList.FindAll(x => x.USEABLE_MONSTER_TYPE == find);
	}
	public Row Find_keyName(string find)
	{
		return rowList.Find(x => x.REAL_NAME == find);
	}
	public List<Row> FindAll_keyName(string find)
	{
		return rowList.FindAll(x => x.REAL_NAME == find);
	}
	public Row Find_AT(string find)
	{
		return rowList.Find(x => x.ATTACK_WEIGHT == find);
	}
	public List<Row> FindAll_AT(string find)
	{
		return rowList.FindAll(x => x.ATTACK_WEIGHT == find);
	}
	public Row Find_attackType(string find)
	{
		return rowList.Find(x => x.ATTACK_TYPE == find);
	}
	public List<Row> FindAll_attackType(string find)
	{
		return rowList.FindAll(x => x.ATTACK_TYPE == find);
	}
	public Row Find_SPLevel(string find)
	{
		return rowList.Find(x => x.SP_LEVEL == find);
	}
	public List<Row> FindAll_SPLevel(string find)
	{
		return rowList.FindAll(x => x.SP_LEVEL == find);
	}
    public Row Find_rarelevel(string find)
    {
        return rowList.Find(x => x.RARITY_LEVEL == find);
    }
    public List<Row> FindAll_rarelevel(string find)
    {
        return rowList.FindAll(x => x.RARITY_LEVEL == find);
    }

}