// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using System.Text;

public class SkillConfigTable
{
	public class Row
	{
		public string ID;
		public string type;
		public string keyName;
		public string ShowName;
		public string SkillPoint;
		public string attackType;
		public string AI_close;
		public string AI_near;
		public string AI_far;
        public string AI_out;
		public string SPLevel;
		public string canAirTrigger;
        public string skillEmergentLevel;
        public string rarelevel;
    }

	public List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

    public void SaveByCurrentRows(string filePath)
    {
        List<Row> toDeleteList = new List<Row>();
        foreach(Row row in rowList)
        {
            if (row.keyName == null || row.ID == null || row.ID == "" || int.Parse(row.ID) < 0 )
                toDeleteList.Add(row);
        }
        foreach(Row row in toDeleteList)
        {
            Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
            rowList.Remove(row);
        }

        string[][] grid = new string[rowList.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[14];
            if (i == 0)
            {
                grid[i][0] = "ID";
                grid[i][1] = "type";
                grid[i][2] = "keyName";
                grid[i][3] = "ShowName";
                grid[i][4] = "SkillPoint";
                grid[i][5] = "attackType";
                grid[i][6] = "AI_close";
                grid[i][7] = "AI_near";
                grid[i][8] = "AI_far";
                grid[i][9] = "AI_out";
                grid[i][10] = "SPLevel";
                grid[i][11] = "canAirTrigger";
                grid[i][12] = "skillEmergentLevel";
                grid[i][13] = "rarelevel";
            }
            else
            {
                grid[i][0] = rowList[i - 1].ID;
                grid[i][1] = rowList[i - 1].type;
                grid[i][2] = rowList[i - 1].keyName;
                grid[i][3] = rowList[i - 1].ShowName;
                grid[i][4] = rowList[i - 1].SkillPoint;
                grid[i][5] = rowList[i - 1].attackType;
                grid[i][6] = rowList[i - 1].AI_close;
                grid[i][7] = rowList[i - 1].AI_near;
                grid[i][8] = rowList[i - 1].AI_far;
                grid[i][9] = rowList[i - 1].AI_out;
                grid[i][10] = rowList[i - 1].SPLevel;
                grid[i][11] = rowList[i - 1].canAirTrigger;
                grid[i][12] = rowList[i - 1].skillEmergentLevel;
                grid[i][13] = rowList[i - 1].rarelevel;
            }
        }
        string delimiter = ",";
        StringBuilder sb = new StringBuilder();

        for (int index = 0; index < grid.Length; index++)
            sb.AppendLine(string.Join(delimiter, grid[index]));

        Debug.Log("尝试最终保存文件" + filePath);
        StreamWriter outStream = System.IO.File.CreateText(filePath);
        outStream.WriteLine(sb);
        outStream.Close();
    }

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);

        try
        {
            for (int i = 1; i < grid.Length; i++)
            {
                if (grid[i].Length == 14)
                {
                    Row row = new Row();
                    row.ID = grid[i][0];
                    row.type = grid[i][1];
                    row.keyName = grid[i][2];
                    row.ShowName = grid[i][3];
                    row.SkillPoint = grid[i][4];
                    row.attackType = grid[i][5];
                    row.AI_close = grid[i][6];
                    row.AI_near = grid[i][7];
                    row.AI_far = grid[i][8];
                    row.AI_out = grid[i][9];
                    row.SPLevel = grid[i][10];
                    row.canAirTrigger = grid[i][11];
                    row.skillEmergentLevel = grid[i][12];
                    row.rarelevel = grid[i][13];
                    rowList.Add(row);
                }
            }
            isLoaded = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
    }

    public void UpdateSkillConfigTableFile(TextAsset oldFile)
    {
    
    }

    public IDictionary<int,SkillConfig> getSkillConfigDic()
    {
        IDictionary<int, SkillConfig> Dic = new Dictionary<int, SkillConfig>();

        List<SkillConfig> ALL = RowsToSkillConfigList(this.rowList);
        foreach (SkillConfig keyValuePair in ALL)
        {
            if (!Dic.ContainsKey(keyValuePair.id))
                Dic.Add(new KeyValuePair<int, SkillConfig>(keyValuePair.id, keyValuePair));
            else
                Debug.Log("致命错误「技能配置文件」技能ID重复："+ keyValuePair .id);
        }
        return Dic;
    }

    public List<SkillConfig> RowsToSkillConfigList(List<Row> Rows)
    {
        List<SkillConfig> skillConfigs = new List<SkillConfig>();
        foreach(Row row in Rows)
        {
            SkillConfig newConfig = RowToSkillConfig(row);
            if (newConfig != null)
                skillConfigs.Add(newConfig);
        }
        return skillConfigs;
    }

    public Row SkillConfigToRow(SkillConfig skillConfig)
    {
        if (skillConfig == null)
            return null;
        Row row = new Row();

        row.ID = skillConfig.id.ToString();
        row.type = skillConfig.type;
        row.keyName = skillConfig.keyName;
        row.ShowName = skillConfig.ShowName;
        row.SkillPoint = skillConfig.SkillPoint.ToString();

        switch (skillConfig.stateType)
        {
            case stateType.GR:
                row.attackType = "GR";
                break;
            case stateType.GI:
                row.attackType = "GI";
                break;
            case stateType.GM:
                row.attackType = "GM";
                break;
            case stateType.CT:
                row.attackType = "CT";
                break;
            case stateType.NONE:
                row.attackType = "NONE";
                break;
        }

        if (skillConfig.ai_trigger_ranges.Contains(behaviorEnterRange.inner_range))
            row.AI_close = "TRUE";
        else
            row.AI_close = "FALSE";
        if (skillConfig.ai_trigger_ranges.Contains(behaviorEnterRange.mid_range))
            row.AI_near = "TRUE";
        else
            row.AI_near = "FALSE";
        if (skillConfig.ai_trigger_ranges.Contains(behaviorEnterRange.far_range))
            row.AI_far = "TRUE";
        else
            row.AI_far = "FALSE";
        if (skillConfig.ai_trigger_ranges.Contains(behaviorEnterRange.out_of_range))
            row.AI_out = "TRUE";
        else
            row.AI_out = "FALSE";

        switch (skillConfig.SPLevel)
        {
            case EX.normal:
                row.SPLevel = "normal";
                break;
            case EX.EX1:
                row.SPLevel = "EX1";
                break;
            case EX.EX2:
                row.SPLevel = "EX2";
                break;
            case EX.EX3:
                row.SPLevel = "EX3";
                break;
            default:
                row.SPLevel = "NULL";
                break;
        }

        switch (skillConfig.canAirTrigger)
        {
            case true:
                row.canAirTrigger = "TRUE";
                break;
            case false:
                row.canAirTrigger = "FALSE";
                break;
        }

        switch (skillConfig.skillEmergentLevel)
        {
            case skillEmergentLevel.level1:
                row.skillEmergentLevel = "1";
                break;
            case skillEmergentLevel.level2:
                row.skillEmergentLevel = "2";
                break;
            case skillEmergentLevel.level3:
                row.skillEmergentLevel = "3";
                break;
            case skillEmergentLevel.none:
                row.skillEmergentLevel = "0";
                break;
        }

        row.rarelevel = skillConfig.rarelevel.ToString();

        return row;
    }

    public SkillConfig RowToSkillConfig(Row row)
    {
        if (row == null)
            return null;
        SkillConfig _SkillConfig = new SkillConfig();
        _SkillConfig.id = int.Parse(row.ID);
        _SkillConfig.type = row.type;
        _SkillConfig.keyName = row.keyName;
        _SkillConfig.ShowName = row.ShowName;
        _SkillConfig.SkillPoint = int.Parse(row.SkillPoint);

        switch(row.attackType)
        {
            case "GR":
                _SkillConfig.stateType = stateType.GR;
                break;
            case "GI":
                _SkillConfig.stateType = stateType.GI;
                break;
            case "GM":
                _SkillConfig.stateType = stateType.GM;
                break;
            case "CT":
                _SkillConfig.stateType = stateType.CT;
                break;
            case "NONE":
                _SkillConfig.stateType = stateType.NONE;
                break;
        }

        List<behaviorEnterRange> ranges = new List<behaviorEnterRange>();
        if (row.AI_close == "TRUE")
            ranges.Add(behaviorEnterRange.inner_range);
        if (row.AI_near == "TRUE")
            ranges.Add(behaviorEnterRange.mid_range);
        if (row.AI_far == "TRUE")
            ranges.Add(behaviorEnterRange.far_range);
        if (row.AI_out == "TRUE")
            ranges.Add(behaviorEnterRange.out_of_range);
        _SkillConfig.ai_trigger_ranges = ranges.ToArray();

        switch(row.SPLevel)
        {
            case "normal":
                _SkillConfig.SPLevel = EX.normal;
                break;
            case "EX1":
                _SkillConfig.SPLevel = EX.EX1;
                break;
            case "EX2":
                _SkillConfig.SPLevel = EX.EX2;
                break;
            case "EX3":
                _SkillConfig.SPLevel = EX.EX3;
                break;
            default:
                _SkillConfig.SPLevel = EX.NULL;
                break;
        }

        switch (row.canAirTrigger)
        {
            case "TRUE":
                _SkillConfig.canAirTrigger = true;
                break;
            case "FALSE":
                _SkillConfig.canAirTrigger = false;
                break;
        }

        switch(row.skillEmergentLevel)
        {
            case "0":
                _SkillConfig.skillEmergentLevel = skillEmergentLevel.none;
                break;
            case "1":
                _SkillConfig.skillEmergentLevel = skillEmergentLevel.level1;
                break;
            case "2":
                _SkillConfig.skillEmergentLevel = skillEmergentLevel.level2;
                break;
            case "3":
                _SkillConfig.skillEmergentLevel = skillEmergentLevel.level3;
                break;
        }

        _SkillConfig.rarelevel = int.Parse(row.rarelevel);

        return _SkillConfig;
    }

    public List<Row> FindAll_type_keyName(string type, string keyName)
    {
        return (rowList.FindAll(x => x.keyName == keyName).Intersect(rowList.FindAll(x => x.type == type))).ToList();
    }

    public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_ID(string find)
	{
		return rowList.Find(x => x.ID == find);
	}
	public List<Row> FindAll_ID(string find)
	{
		return rowList.FindAll(x => x.ID == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}
	public Row Find_keyName(string find)
	{
		return rowList.Find(x => x.keyName == find);
	}
	public List<Row> FindAll_keyName(string find)
	{
		return rowList.FindAll(x => x.keyName == find);
	}
	public Row Find_ShowName(string find)
	{
		return rowList.Find(x => x.ShowName == find);
	}
	public List<Row> FindAll_ShowName(string find)
	{
		return rowList.FindAll(x => x.ShowName == find);
	}
	public Row Find_SkillPoint(string find)
	{
		return rowList.Find(x => x.SkillPoint == find);
	}
	public List<Row> FindAll_SkillPoint(string find)
	{
		return rowList.FindAll(x => x.SkillPoint == find);
	}
	public Row Find_attackType(string find)
	{
		return rowList.Find(x => x.attackType == find);
	}
	public List<Row> FindAll_attackType(string find)
	{
		return rowList.FindAll(x => x.attackType == find);
	}
	public Row Find_AI_close(string find)
	{
		return rowList.Find(x => x.AI_close == find);
	}
	public List<Row> FindAll_AI_close(string find)
	{
		return rowList.FindAll(x => x.AI_close == find);
	}
	public Row Find_AI_near(string find)
	{
		return rowList.Find(x => x.AI_near == find);
	}
	public List<Row> FindAll_AI_near(string find)
	{
		return rowList.FindAll(x => x.AI_near == find);
	}
	public Row Find_AI_far(string find)
	{
		return rowList.Find(x => x.AI_far == find);
	}
	public List<Row> FindAll_AI_far(string find)
	{
		return rowList.FindAll(x => x.AI_far == find);
	}
    public Row Find_AI_out(string find)
    {
        return rowList.Find(x => x.AI_out == find);
    }
    public List<Row> FindAll_AI_out(string find)
    {
        return rowList.FindAll(x => x.AI_out == find);
    }
	public Row Find_SPLevel(string find)
	{
		return rowList.Find(x => x.SPLevel == find);
	}
	public List<Row> FindAll_SPLevel(string find)
	{
		return rowList.FindAll(x => x.SPLevel == find);
	}
	public Row Find_canAirTrigger(string find)
	{
		return rowList.Find(x => x.canAirTrigger == find);
	}
	public List<Row> FindAll_canAirTrigger(string find)
	{
		return rowList.FindAll(x => x.canAirTrigger == find);
	}
    public Row Find_skillEmergentLevel(string find)
    {
        return rowList.Find(x => x.skillEmergentLevel == find);
    }
    public List<Row> FindAll_skillEmergentLevel(string find)
    {
        return rowList.FindAll(x => x.skillEmergentLevel == find);
    }
    public Row Find_rarelevel(string find)
    {
        return rowList.Find(x => x.rarelevel == find);
    }
    public List<Row> FindAll_rarelevel(string find)
    {
        return rowList.FindAll(x => x.rarelevel == find);
    }

}