// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

public class HitBoxLogTable
{
    static HitBoxLogTable instance;
    public static HitBoxLogTable Instance
    {
        get
        {
            if (instance == null)
            {
                instance = new HitBoxLogTable();
            }
            return instance;
        }
    }
    
	public class Row
	{
		public string RECORD_ID;
		public string REAL_NAME;
		public string USEABLE_MONSTER_TYPE;
		public string Untouched;
		public string Touched;
		public string Successed;
	}

	public List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.RECORD_ID = grid[i][0];
			row.REAL_NAME = grid[i][1];
			row.USEABLE_MONSTER_TYPE = grid[i][2];
			row.Untouched = grid[i][3];
			row.Touched = grid[i][4];
			row.Successed = grid[i][5];
			rowList.Add(row);
		}
		isLoaded = true;
	}
    
    public void Load(string csv)
    {
        rowList.Clear();
        string[][] grid = CsvParser2.Parse(csv);
        for(int i = 1 ; i < grid.Length ; i++)
        {
            if (grid[i].Length == 0)
            {
                continue;
            }
            Row row = new Row();
            row.RECORD_ID = grid[i][0];
            row.REAL_NAME = grid[i][1];
            row.USEABLE_MONSTER_TYPE = grid[i][2];
            row.Untouched = grid[i][3];
            row.Touched = grid[i][4];
            row.Successed = grid[i][5];
            rowList.Add(row);
        }
        isLoaded = true;
    }
    
    public void SaveByCurrentRows_HitBoxLog(string filePath, HitBoxLogger hitBoxLogger)
    {
        List<Row> toDeleteList = new List<Row>();
        foreach(Row row in rowList)
        {
            if (row.REAL_NAME == null)
                toDeleteList.Add(row);
        }
        foreach(Row row in toDeleteList)
        {
            Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
            rowList.Remove(row);
        }

        string[][] grid = new string[rowList.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[12];
            if (i == 0)
            {
                grid[i][0] = "RECORD_ID";
                grid[i][1] = "REAL_NAME";
                grid[i][2] = "USEABLE_MONSTER_TYPE";
                grid[i][3] = "Untouched";
                grid[i][4] = "Touched";
                grid[i][5] = "Successed";
            }
            else
            {
                if (hitBoxLogger == null)
                {
                    grid[i][0] = rowList[i - 1].RECORD_ID;
                    grid[i][1] = rowList[i - 1].REAL_NAME;
                    grid[i][2] = rowList[i - 1].USEABLE_MONSTER_TYPE;
                    grid[i][3] = "0";
                    grid[i][4] = "0";
                    grid[i][5] = "0";
                }else{
                    grid[i][0] = rowList[i - 1].RECORD_ID;
                    grid[i][1] = rowList[i - 1].REAL_NAME;
                    grid[i][2] = rowList[i - 1].USEABLE_MONSTER_TYPE;
                    grid[i][3] = ((hitBoxLogger.untouchedtimes.ContainsKey(grid[i][1]) ? hitBoxLogger.untouchedtimes[grid[i][1]] : 0) + int.Parse(rowList[i - 1].Untouched)).ToString();
                    grid[i][4] = ((hitBoxLogger.touchedtimes.ContainsKey(grid[i][1]) ? hitBoxLogger.touchedtimes[grid[i][1]] : 0) + int.Parse(rowList[i - 1].Touched)).ToString();
                    grid[i][5] = ((hitBoxLogger.successedtimes.ContainsKey(grid[i][1]) ? hitBoxLogger.successedtimes[grid[i][1]] : 0) + int.Parse(rowList[i - 1].Successed)).ToString();
                }

            }
        }
        string delimiter = ",";
        StringBuilder sb = new StringBuilder();
        for (int index = 0; index < grid.Length; index++)
            sb.AppendLine(string.Join(delimiter, grid[index]));
        Debug.Log("尝试最终保存文件" + filePath);
        StreamWriter outStream = System.IO.File.CreateText(filePath);
        outStream.WriteLine(sb);
        outStream.Close();
    }
    
	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_RECORD_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
	public Row Find_REAL_NAME(string find)
	{
		return rowList.Find(x => x.REAL_NAME == find);
	}
	public List<Row> FindAll_REAL_NAME(string find)
	{
		return rowList.FindAll(x => x.REAL_NAME == find);
	}
	public Row Find_USEABLE_MONSTER_TYPE(string find)
	{
		return rowList.Find(x => x.USEABLE_MONSTER_TYPE == find);
	}
	public List<Row> FindAll_USEABLE_MONSTER_TYPE(string find)
	{
		return rowList.FindAll(x => x.USEABLE_MONSTER_TYPE == find);
	}
	public Row Find_Untouched(string find)
	{
		return rowList.Find(x => x.Untouched == find);
	}
	public List<Row> FindAll_Untouched(string find)
	{
		return rowList.FindAll(x => x.Untouched == find);
	}
	public Row Find_Touched(string find)
	{
		return rowList.Find(x => x.Touched == find);
	}
	public List<Row> FindAll_Touched(string find)
	{
		return rowList.FindAll(x => x.Touched == find);
	}
	public Row Find_Successed(string find)
	{
		return rowList.Find(x => x.Successed == find);
	}
	public List<Row> FindAll_Successed(string find)
	{
		return rowList.FindAll(x => x.Successed == find);
	}
}