// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Skill;

public class INHERENT_SkillTable
{
	public class Row
	{
		public string RECORD_ID;
		public string MONSTER_ID;
		public string SKILL_ID;
	}
    
    static readonly List<Row> rowList = new List<Row>();
    static bool isLoaded;
    
    public static bool IsLoaded()
    {
        return isLoaded;
    }
    
    public static IDictionary<string, string> GetINHERENTSKIDList(string monsterID)
    {
        IDictionary<string, string> targets = new Dictionary<string, string>();
        List<Row> rows = FindAll_MONSTER_ID(monsterID);
        for (int i = 0; i < rows.Count; i++)
        {
            if (!targets.ContainsKey(rows[i].SKILL_ID))
            {
                SkillConfig _SkillConfig = SkillConfigTable.GetSkillConfigByID(rows[i].SKILL_ID);
                if (_SkillConfig == null)
                {
                    Debug.Log("严重问题：被动技能表里定义的技能在总技能表里没有对应ID");
                    continue;
                }
                targets.Add(rows[i].SKILL_ID, _SkillConfig.REAL_NAME);
            }
        }
        return targets;
    }
    
    public List<Row> GetRowList()
    {
        return rowList;
    }
    
    public static IEnumerator LoadAllINHERENTSkillConfigs()
    {
        switch (ResourceLoadingSetting.ConfigFileLoadingMode)
        {
            case ResourceLoadMode.CachAB:
                break;
            case ResourceLoadMode.StreamingAssetAB:
                break;
            case ResourceLoadMode.Resource:
                LoadINHERENTSkillsByLocalConfigFile();
                break;
        }
        yield break;
    }
    
    public static void LoadINHERENTSkillsByLocalConfigFile()
    {
        TextAsset csv = Resources.Load("Account/INHERENT_SKILL") as TextAsset;
        if (csv != null)
        {
            Load(csv);
        }
    }
    
	public static void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
            if (!string.IsNullOrEmpty(grid[i][1]) && !string.IsNullOrEmpty(grid[i][2]))
            {
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    MONSTER_ID = grid[i][1],
                    SKILL_ID = grid[i][2]
                };
                rowList.Add(row);
            }
		}
		isLoaded = true;
	}
    
	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
        return rowList.Count <= i ? null : rowList[i];
    }

    public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_RECORD_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
	public Row Find_MONSTER_ID(string find)
	{
		return rowList.Find(x => x.MONSTER_ID == find);
	}
	public static List<Row> FindAll_MONSTER_ID(string find)
	{
		return rowList.FindAll(x => x.MONSTER_ID == find);
	}
	public Row Find_SKILL_ID(string find)
	{
		return rowList.Find(x => x.SKILL_ID == find);
	}
	public List<Row> FindAll_SKILL_ID(string find)
	{
		return rowList.FindAll(x => x.SKILL_ID == find);
	}
}