// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class INHERENT_SkillTable
{
	public class Row
	{
		public string RECORD_ID;
		public string MONSTER_ID;
		public string SKILL_ID;
	}
    
    static readonly List<Row> rowList = new List<Row>();
    static bool isLoaded = false;
    
    public static bool IsLoaded()
    {
        return isLoaded;
    }
    
    public static List<string> GetINHERENTSKIDList(string monsterID)
    {
        List<Row> rows = FindAll_MONSTER_ID(monsterID);
        List<string> skillIds = new List<string>();
        for (int i = 0; i < rows.Count; i++)
        {
            if (!skillIds.Contains(rows[i].SKILL_ID))
            {
                skillIds.Add(rows[i].SKILL_ID);
            }
        }
        return skillIds;
    }
    
    public List<Row> GetRowList()
    {
        return rowList;
    }
    
    public static IEnumerator LoadAllINHERENTSkillConfigs()
    {
        switch (ResourceLoadingSetting.ConfigFileLoadingMode)
        {
            case ResourceLoadMode.CachAB:
                break;
            case ResourceLoadMode.StreamingAssetAB:
                break;
            case ResourceLoadMode.Resource:
                LoadINHERENTSkillsByLocalConfigFile();
                break;
        }
        yield break;
    }
    
    public static void LoadINHERENTSkillsByLocalConfigFile()
    {
        TextAsset csv = Resources.Load("Account/INHERENT_SKILL") as TextAsset;
        if (csv != null)
        {
            Load(csv);
        }
    }

	public static void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
            if (!string.IsNullOrEmpty(grid[i][1]) && !string.IsNullOrEmpty(grid[i][2]))
            {
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    MONSTER_ID = grid[i][1],
                    SKILL_ID = grid[i][2]
                };
                rowList.Add(row);
            }
		}
		isLoaded = true;
	}
    
	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_RECORD_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
	public Row Find_MONSTER_ID(string find)
	{
		return rowList.Find(x => x.MONSTER_ID == find);
	}
	public static List<Row> FindAll_MONSTER_ID(string find)
	{
		return rowList.FindAll(x => x.MONSTER_ID == find);
	}
	public Row Find_SKILL_ID(string find)
	{
		return rowList.Find(x => x.SKILL_ID == find);
	}
	public List<Row> FindAll_SKILL_ID(string find)
	{
		return rowList.FindAll(x => x.SKILL_ID == find);
	}
}