// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class SkillNameTable
{
	public class Row
	{
		public string RECORD_ID;
		public string SKILL_ID;
		public string EN_NAME;
		public string JP_NAME;
		public string CN_NAME;
	}
    
    static IDictionary<string, string> SkillNameDic = new Dictionary<string, string>();
	static List<Row> rowList = new List<Row>();
	static bool isLoaded;
    
    public static string GetSkillName(string recordId)
    {
        if (SkillNameDic.ContainsKey(recordId))
            return SkillNameDic[recordId];
        return "UnKnown";
    }
    
    public static void PrepareSkillNames(ApiLanguage apiLanguage)
    {
        foreach (Row row in rowList)
        {
            if (!SkillNameDic.ContainsKey(row.SKILL_ID))
            {
                switch (apiLanguage)
                {
                    case ApiLanguage.EnUs:
                        SkillNameDic.Add(row.SKILL_ID,row.EN_NAME);
                    break;
                    case ApiLanguage.JaJp:
                        SkillNameDic.Add(row.SKILL_ID,row.JP_NAME);
                    break;
                    case ApiLanguage.ZhCn:
                        SkillNameDic.Add(row.SKILL_ID,row.CN_NAME);
                    break;
                    default:
                        SkillNameDic.Add(row.SKILL_ID,row.EN_NAME);
                    break;
                }
            }
        }
    }
    
    public static IEnumerator LoadSkillNames()
    {
        switch (ResourceLoadingSetting.ConfigFileLoadingMode)
        {
            case ResourceLoadMode.CachAB:
                break;
            case ResourceLoadMode.StreamingAssetAB:
                break;
            case ResourceLoadMode.Resource:
                LoadAllSkillNamesFromLocalConfigFile();
                break;
        }
        yield break;
    }
    
	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

    static void Load(TextAsset csv)
    {
        Debug.Log("尝试读取技能名文档");
    	rowList.Clear();
    	string[][] grid = CsvParser2.Parse(csv.text);
    	for(int i = 1 ; i < grid.Length ; i++)
    	{
            Row row = new Row
            {
                RECORD_ID = grid[i][0],
                SKILL_ID = grid[i][1],
                EN_NAME = grid[i][2],
                JP_NAME = grid[i][3],
                CN_NAME = grid[i][4]
            };
            rowList.Add(row);
    	}
        PrepareSkillNames(Setting.Language);
    	isLoaded = true;
    }
    
    public static void LoadAllSkillNamesFromLocalConfigFile()
    {
        TextAsset csv = Resources.Load("Account/skill_name") as TextAsset;
        if (csv != null)
        {
            Load(csv);
        }
    }

	public int NumRows()
	{
		return rowList.Count;
	}
    
	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_RECORD_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
	public Row Find_SKILL_ID(string find)
	{
		return rowList.Find(x => x.SKILL_ID == find);
	}
	public List<Row> FindAll_SKILL_ID(string find)
	{
		return rowList.FindAll(x => x.SKILL_ID == find);
	}
	public Row Find_EN_NAME(string find)
	{
		return rowList.Find(x => x.EN_NAME == find);
	}
	public List<Row> FindAll_EN_NAME(string find)
	{
		return rowList.FindAll(x => x.EN_NAME == find);
	}
	public Row Find_JP_NAME(string find)
	{
		return rowList.Find(x => x.JP_NAME == find);
	}
	public List<Row> FindAll_JP_NAME(string find)
	{
		return rowList.FindAll(x => x.JP_NAME == find);
	}
	public Row Find_CN_NAME(string find)
	{
		return rowList.Find(x => x.CN_NAME == find);
	}
	public List<Row> FindAll_CN_NAME(string find)
	{
		return rowList.FindAll(x => x.CN_NAME == find);
	}

}