// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;
using Skill;
using System.IO;
using System.Text;
using HittingDetection;
using System;

// 本结构唯一的作用是主界面略览技能详情的时候提供一个大概的数值，
// 任何已经登陆了的技能，如果在本表内没有条目，则会在技能详情画面报错。

public class PowerEstimateTable
{
	public class Row
	{
		public string RECORD_ID;
		public string REAL_NAME;
		public string SPLevel;
		public string EstimateDamage;
		public string HP;
	}

    static readonly List<Row> rowList = new List<Row>();
    static bool isLoaded = false;
    
    public static void Save(string type)
    {
        var SkillConfigs = SkillConfigTable.GetSkillConfigsOfType(type);
        var AnimDic = SKillAnalyzer.AllSkillAnims(type);
        Save(Application.dataPath + "/" +KeywordSetting._SkillStaticAnalysis + ".csv", SkillConfigs, AnimDic);
    }
    
    static void Save(string filepath, List<SkillConfig> SkillConfigs, IDictionary<string, AnimationClip> AnimDic)
    {
        rowList.Clear();
        string[][] grid = new string[SkillConfigs.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[5];
            if (i == 0)
            {
                grid[i][0] = "RECORD_ID";
                grid[i][1] = "REAL_NAME";
                grid[i][2] = "SPLevel";
                grid[i][3] = "EstimateDamage";
                grid[i][4] = "HP";
            }
            else
            {
                grid[i][0] = SkillConfigs[i - 1].RECORD_ID;
                grid[i][1] = SkillConfigs[i - 1].REAL_NAME;
                grid[i][2] = SkillConfigs[i - 1].SP_LEVEL.ToString();
                AnimDic.TryGetValue(SkillConfigs[i -1].REAL_NAME, out AnimationClip clip);
                grid[i][3] = ATCal(clip, SkillConfigs[i - 1].ATTACK_WEIGHT).ToString();
                grid[i][4] = SkillConfigs[i - 1].HP_WEIGHT.ToString();
                
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    REAL_NAME = grid[i][1],
                    SPLevel = grid[i][2],
                    EstimateDamage = grid[i][3],
                    HP = grid[i][4]
                };
                rowList.Add(row);
            }
        }
        
        var delimiter = ",";
        var sb = new StringBuilder();
        foreach (var t in grid)
            sb.AppendLine(string.Join(delimiter, t));
        Debug.Log("尝试最终保存文件" + filepath);
        StreamWriter outStream = File.CreateText(filepath);
        outStream.WriteLine(sb);
        outStream.Close();
    }
    
    public static void LoadByResource()
    {
        //暂时做如下处理
        TextAsset CSV = Resources.Load("Account/" + KeywordSetting._SkillStaticAnalysis) as TextAsset;
        if (CSV)
        {
            Load(CSV.text);
        }
        else
            Debug.Log("没能读取到技能数值参考文件。"+KeywordSetting._SkillStaticAnalysis);
    }
    
    static void Load(string text)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(text);
        try
        {
            Debug.Log(grid);
            for(int i = 1 ; i < grid.Length ; i++)
            {
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    REAL_NAME = grid[i][1],
                    SPLevel = grid[i][2],
                    EstimateDamage = grid[i][3],
                    HP = grid[i][4]
                };
                rowList.Add(row);
            }
            isLoaded = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
	}
    
	public static Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
    
    static float ATCal(AnimationClip _clip, float skillATRef)
    {
        float amount = 0;
        for (int i = 0; i < _clip.events.Length; i++)
        {
            #region 拳脚攻击
            if (SKillAnalyzer.AttackFrameStartMethodNames.Contains(_clip.events[i].functionName) && _clip.events[i].intParameter != 0)
            {
                amount += skillATRef;
            }
            if (_clip.events[i].functionName == "SetAllBodyMarkerManagersIn")
            {
                amount += skillATRef;
            }
            if (_clip.events[i].functionName == "ClearTargets")
            {
                amount += skillATRef;
            }
            if (_clip.events[i].functionName == "EnableMarkers")
            {
                amount += skillATRef;
            }
            #endregion
                        
            #region MagicForward
            if (_clip.events[i].functionName == "MagicForward")
            {
                var magicObjectName = _clip.events[i].stringParameter;
                var hurtObject = Resources.Load("HurtObjects/defaultmagic/" + magicObjectName) as GameObject;
                var hitBox = hurtObject.GetComponent<HitBoxManager>();
                if (hitBox == null)
                {
                    Debug.Log("请检查这个技能动画:" + _clip.name + ",与此伤害物体：" + magicObjectName);
                }
                amount += hitBox.AT_weight * skillATRef;
                
                Decompositioner decompositioner = hurtObject.GetComponent<Decompositioner>();
                if (decompositioner.Attachments.Length > 0)
                {
                    Debug.Log("技能动画："+_clip.name + " 不好机械评估");
                    return -999f;
                }
                
                //// 顺便检查attachment，与攻击力预估无关 /////
                for (int z = 0; z < decompositioner.Attachments.Length; z++)
                {
                    var attachment = Resources.Load("HurtObjects/defaultmagic/" + decompositioner.Attachments[z]) as GameObject;
                    var attachments = attachment.GetComponent<HitBoxManager>();
                    if (attachments == null)
                    {
                        Debug.Log("请检查这个技能动画:" + _clip.name + ",与此伤害物体：" + magicObjectName + "其附属物件资源"+ decompositioner.Attachments[z] + "不存在");
                    }
                }
                ///////////////////////////////////////////
            }
            #endregion
            
            #region 几个固定魔法
            if (_clip.events[i].functionName == "Bullet_shoot_from_body_part" || _clip.events[i].functionName == "BlastAttack")
            {
                amount += skillATRef;
            }
            #endregion
            
            if (_clip.events[i].functionName == "PrepareOneMagic")
            {
                float oneDamege;
                string magicobjectname = _clip.events[i].stringParameter;
                GameObject hurtObject = Resources.Load("HurtObjects/defaultmagic/" + magicobjectname) as GameObject;
                var hitBox = hurtObject.GetComponent<HitBoxManager>();
                oneDamege = hitBox.AT_weight * skillATRef;
                var decompositioner = hurtObject.GetComponent<Decompositioner>();
                if ( decompositioner.Attachments.Length > 0)
                {
                    Debug.Log("技能动画："+_clip.name + " 不好机械评估");
                    return -999f;
                }
                
                //// 顺便检查attachment，与攻击力预估无关 /////
                for (int z = 0; z < decompositioner.Attachments.Length; z++)
                {
                    var attachment = Resources.Load("HurtObjects/defaultmagic/" + decompositioner.Attachments[z]) as GameObject;
                    var attachments = attachment.GetComponent<HitBoxManager>();
                    if (attachments == null)
                    {
                        Debug.Log("请检查这个技能动画:" + _clip.name + ",与此伤害物体：" + magicobjectname + "其附属物件资源"+ decompositioner.Attachments[z] + "不存在");
                    }
                }
                ///////////////////////////////////////////
                
                for (int y = i + 1; y < _clip.events.Length; y++)
                {
                    if (_clip.events[y].functionName == "ReleasePreparedMagic" || _clip.events[y].functionName == "ReleasePreparedMagicToAir")
                    {
                        //Debug.Log(_clip.name + ":" + _clip.events[y].functionName + "伤害估值增加："+ oneDamege);
                        amount += oneDamege;
                    }
                    // 第二次遇到PrepareOneMagic说明换魔法了。一个技能两次PrepareOneMagic目前其实还没有
                    if (_clip.events[y].functionName == "PrepareOneMagic")
                    {
                        Debug.Log(_clip.name + "出现两次PrepareOneMagic");
                        break;
                    }
                }
            }
        }
        return amount;
    }
}