// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using System.Text;
using Skill;

public partial class SkillConfigTable
{
    public static IDictionary<string, SkillConfig> SkillConfigRefDic = new Dictionary<string, SkillConfig>();
       
    public class Row
    {
        public string RECORD_ID;
        public string REAL_NAME;
        public string USEABLE_MONSTER_TYPE;
        public string ATTACK_WEIGHT;
        public string HP_WEIGHT;
        public string ATTACK_TYPE;
        public string SP_LEVEL;
        public string TRIGGER_DIS_MIN;
        public string TRIGGER_DIS_MAX;
        public string EVENT_CODE;
        public string RARITY_LEVEL;
    }

    public static List<Row> rowList = new List<Row>();
    
    static bool isLoaded;
    public static bool IsLoaded()
    {
    	return isLoaded;
    }
    
    public static IEnumerator LoadAllSkillConfigs()
    {
        switch (ResourceLoadingSetting.ConfigFileLoadingMode)
        {
            case ResourceLoadMode.CachAB:
                break;
            case ResourceLoadMode.StreamingAssetAB:
                break;
            case ResourceLoadMode.Resource:
                LoadAllSkillConfigFromLocalConfigFile();
                break;
        }
        yield return INHERENT_SkillTable.LoadAllINHERENTSkillConfigs();// 角色原生技能的load和技能表load同步进行。
        yield break;
    }
    
    static void RefreshSkillConfigDicForReference()// 下午从这个开始研究。
    {
        IDictionary<string, SkillConfig> Dic = new Dictionary<string, SkillConfig>();
        List<SkillConfig> ALL = RowsToSkillConfigList(rowList);
        foreach (SkillConfig keyValuePair in ALL)
        {
            if (!Dic.ContainsKey(keyValuePair.RECORD_ID))
            {
                Dic.Add(new KeyValuePair<string, SkillConfig>(keyValuePair.RECORD_ID, keyValuePair));
                //Debug.Log("以下技能加入字典： RECORDID:"+keyValuePair.RECORD_ID + "  realname:"+ keyValuePair.REAL_NAME);
            }
            else
            {
                Debug.Log("致命错误「技能配置文件」技能ID重复：" + keyValuePair.RECORD_ID);
            }
        }
        Debug.Log("已读取共"+ Dic.Count + "个技能");
        SkillConfigRefDic = Dic;
    }
    
    public static SkillConfig GetSkillConfigByID(string ID)
    {
        if (ID != null)
        {
            SkillConfigRefDic.TryGetValue(ID, out SkillConfig skillConfig);
            return skillConfig;
        }else{
            return null;
        }
    }
    
    public static List<SkillConfig> GetSkillConfigsOfType(string type)
    {
        List<SkillConfig> SkillConfigsOfType = new List<SkillConfig>();
        foreach (KeyValuePair<string, SkillConfig> one in SkillConfigRefDic)
        {
            if (one.Value.TYPE == type)
                SkillConfigsOfType.Add(one.Value);
        }
        return SkillConfigsOfType;
    }
    
    public static void LoadAllSkillConfigFromLocalConfigFile()
    {
        TextAsset csv = Resources.Load("Account/mst_skill") as TextAsset;
        if (csv != null)
        {
            Load(csv);
        }
    }
    
    public static void SaveByCurrentRows(string filePath)
    {
        List<Row> toDeleteList = new List<Row>();
        foreach(Row row in rowList)
        {
            if (row.REAL_NAME == null)
                toDeleteList.Add(row);
        }
        foreach(Row row in toDeleteList)
        {
            Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
            rowList.Remove(row);
        }

        string[][] grid = new string[rowList.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[12];
            if (i == 0)
            {
                grid[i][0] = "RECORD_ID";
                grid[i][1] = "REAL_NAME";
                grid[i][2] = "USEABLE_MONSTER_TYPE";
                grid[i][3] = "ATTACK_WEIGHT";
                grid[i][4] = "HP_WEIGHT";
                grid[i][5] = "ATTACK_TYPE";
                grid[i][6] = "SP_LEVEL";
                grid[i][7] = "TRIGGER_DIS_MIN";
                grid[i][8] = "TRIGGER_DIS_MAX";
                grid[i][9] = "CONNATE_CODE";
                grid[i][10] = "RARITY_LEVEL";
            }
            else
            {
                grid[i][0] = rowList[i - 1].RECORD_ID;
                grid[i][1] = rowList[i - 1].REAL_NAME;
                grid[i][2] = rowList[i - 1].USEABLE_MONSTER_TYPE;
                grid[i][3] = rowList[i - 1].ATTACK_WEIGHT;
                grid[i][4] = rowList[i - 1].HP_WEIGHT;
                grid[i][5] = rowList[i - 1].ATTACK_TYPE;
                grid[i][6] = rowList[i - 1].SP_LEVEL;
                grid[i][7] = rowList[i - 1].TRIGGER_DIS_MIN;
                grid[i][8] = rowList[i - 1].TRIGGER_DIS_MAX;
                grid[i][9] = rowList[i - 1].EVENT_CODE;
                grid[i][10] = rowList[i - 1].RARITY_LEVEL;
            }
        }
        string delimiter = ",";
        StringBuilder sb = new StringBuilder();

        for (int index = 0; index < grid.Length; index++)
            sb.AppendLine(string.Join(delimiter, grid[index]));

        Debug.Log("尝试最终保存文件" + filePath);
        StreamWriter outStream = File.CreateText(filePath);
        outStream.WriteLine(sb);
        outStream.Close();
    }
    
	public static void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
        try
        {
            for (int i = 1; i < grid.Length; i++)
            {
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    REAL_NAME = grid[i][1],
                    USEABLE_MONSTER_TYPE = grid[i][2],
                    ATTACK_WEIGHT = grid[i][3],
                    HP_WEIGHT = grid[i][4],
                    ATTACK_TYPE = grid[i][5],
                    SP_LEVEL = grid[i][6],
                    TRIGGER_DIS_MIN = grid[i][7],
                    TRIGGER_DIS_MAX = grid[i][8],
                    EVENT_CODE = grid[i][9],
                    RARITY_LEVEL = grid[i][10]
                };
                rowList.Add(row);
            }
            isLoaded = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
        RefreshSkillConfigDicForReference();
    }
    
    public static List<Row> FindAll_type_keyName(string type, string keyName)
    {
        return (rowList.FindAll(x => x.REAL_NAME == keyName).Intersect(rowList.FindAll(x => x.USEABLE_MONSTER_TYPE == type))).ToList();
    }

    public int NumRows()
	{
		return rowList.Count;
	}
    
    public List<Row> GetRowList()
    {
        return rowList;
    }

	public Row GetAt(int i)
	{
        return rowList.Count <= i ? null : rowList[i];
    }
    
    public Row Find_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
    public Row Find_MONSTER_TYPE_CODE(string find)
    {
    	return rowList.Find(x => x.USEABLE_MONSTER_TYPE == find);
    }
    public static List<Row> FindAll_MONSTER_TYPE(string find)
    {
    	return rowList.FindAll(x => x.USEABLE_MONSTER_TYPE == find);
    }
    public Row Find_keyName(string find)
    {
    	return rowList.Find(x => x.REAL_NAME == find);
    }
    public List<Row> FindAll_keyName(string find)
    {
    	return rowList.FindAll(x => x.REAL_NAME == find);
    }
    public Row Find_AT(string find)
    {
    	return rowList.Find(x => x.ATTACK_WEIGHT == find);
    }
    public List<Row> FindAll_AT(string find)
    {
    	return rowList.FindAll(x => x.ATTACK_WEIGHT == find);
    }
    public Row Find_attackType(string find)
    {
    	return rowList.Find(x => x.ATTACK_TYPE == find);
    }
    public List<Row> FindAll_attackType(string find)
    {
    	return rowList.FindAll(x => x.ATTACK_TYPE == find);
    }
    public Row Find_SPLevel(string find)
    {
    	return rowList.Find(x => x.SP_LEVEL == find);
    }
    public List<Row> FindAll_SPLevel(string find)
    {
    	return rowList.FindAll(x => x.SP_LEVEL == find);
    }
    public Row Find_Rarelevel(string find)
    {
        return rowList.Find(x => x.RARITY_LEVEL == find);
    }
    public List<Row> FindAll_Rarelevel(string find)
    {
        return rowList.FindAll(x => x.RARITY_LEVEL == find);
    }
}