// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using System.Text;
using Skill;

public class MonstersConfigTable
{
    static MonstersConfigTable instance;
    public static MonstersConfigTable Instance
    {
        get
        {
            if (instance == null)
                instance = new MonstersConfigTable();
            return instance;
        }
    }
    public static IDictionary<string, CharConfig> CharacterResourceInfoDic = new Dictionary<string, CharConfig>();

    [Serializable]
    public class Row
	{
		public string RECORD_ID;
        public string REAL_NAME;
        public string MONSTER_TYPE;
		public string ZOKUSEI;
		public string SPECIAL_ZOKUSEI;
        public string RARITY_LEVEL;
		public string BASIC_MOVEMENT_PACK;
		public string MOVE_TYPE;
		public string DODGE_SKILL;
		public string DEFENDABLE_FLAG;
	}
            
    public static CharConfig GetCharConfig(string resourceId)
    {
        return CharacterResourceInfoDic.ContainsKey(resourceId) ? CharacterResourceInfoDic[resourceId] : null;
    }
    public static void LoadMonstersConfigByResource()
    {
        //暂时做如下处理
        TextAsset CSV = Resources.Load("Account/mst_monster") as TextAsset;
        if (CSV)
        {
            Instance.Load(CSV);
        }
        else
            Debug.Log("没能读取到角色数据库文件。");
    }
    
    public static void RefreshCharacterResourceInfoDic()
    {
        CharacterResourceInfoDic.Clear();
        List<CharConfig> characterResourceInfos = Instance.RowToCharacterResourceInfoList(Instance.rowList);
        foreach (CharConfig one in characterResourceInfos)            
        {
            CharacterResourceInfoDic.Add(one.RECORD_ID,one);
        }
    }
    
    public IEnumerator LoadMonstersConfig()
    {
        switch (ResourceLoadingSetting.ConfigFileLoadingMode)
        {
            case ResourceLoadMode.CachAB:
                break;
            case ResourceLoadMode.StreamingAssetAB:
                break;
            case ResourceLoadMode.Resource:
                LoadMonstersConfigByResource();
                break;
        }
        RefreshCharacterResourceInfoDic();
        yield break;    
    }

	public List<Row> rowList = new List<Row>();
	bool isLoaded;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
        try
        {
            for (int i = 1; i < grid.Length; i++)
            {
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    REAL_NAME = grid[i][1],
                    MONSTER_TYPE = grid[i][2],
                    ZOKUSEI = grid[i][3],
                    SPECIAL_ZOKUSEI = grid[i][4],
                    RARITY_LEVEL = grid[i][5],
                    BASIC_MOVEMENT_PACK = grid[i][6],
                    MOVE_TYPE = grid[i][7],
                    DODGE_SKILL = grid[i][8],
                    DEFENDABLE_FLAG = grid[i][9]
                };
                rowList.Add(row);
            }
            isLoaded = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
    }

    public void SaveByCurrentRows(string filePath)
    {
        List<Row> toDeleteList = new List<Row>();
        foreach (Row row in rowList)
        {
            if (row.REAL_NAME == null)
                toDeleteList.Add(row);
        }
        foreach (Row row in toDeleteList)
        {
            Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
            rowList.Remove(row);
        }

        string[][] grid = new string[rowList.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[10];
            if (i == 0)
            {                        
                grid[i][0] = "RECORD_ID";
                grid[i][1] = "REAL_NAME";
                grid[i][2] = "MONSTER_TYPE_CODE";
                grid[i][3] = "ZOKUSEI";
                grid[i][4] = "SPECIAL_ZOKUSEI";
                grid[i][5] = "RARITY_LEVEL";
                grid[i][6] = "BASIC_MOVEMENT_PACK";
                grid[i][7] = "MOVE_TYPE";
                grid[i][8] = "MOTILITY_SKILL_PACK";
                grid[i][9] = "DEFENDABLE_FLAG";
            }
            else
            {
                grid[i][0] = rowList[i - 1].RECORD_ID;
                grid[i][1] = rowList[i - 1].REAL_NAME;
                grid[i][2] = rowList[i - 1].MONSTER_TYPE;
                grid[i][3] = rowList[i - 1].ZOKUSEI;
                grid[i][4] = rowList[i - 1].SPECIAL_ZOKUSEI;
                grid[i][5] = rowList[i - 1].RARITY_LEVEL;
                grid[i][6] = rowList[i - 1].BASIC_MOVEMENT_PACK;
                grid[i][7] = rowList[i - 1].MOVE_TYPE;
                grid[i][8] = rowList[i - 1].DODGE_SKILL;
                grid[i][9] = rowList[i - 1].DEFENDABLE_FLAG;
            }
        }
        string delimiter = ",";
        StringBuilder sb = new StringBuilder();

        for (int index = 0; index < grid.Length; index++)
        {
            sb.AppendLine(string.Join(delimiter, grid[index]));
        }
        
        Debug.Log("尝试最终保存文件" + filePath);
        StreamWriter outStream = File.CreateText(filePath);
        outStream.WriteLine(sb);
        outStream.Close();
    }

    // by haku 9.12
    // filePath的后面记得包括文件名和CSV后缀？
    public void Save(string filePath, List<CharConfig> characterResourceList)
    {
        try
        {
            rowList.Clear();

            foreach (CharConfig characterResourceInfo in characterResourceList)
            {
                Debug.Log("尝试整理角色：" + characterResourceInfo.REAL_NAME);
                Row row = new Row
                {
                    RECORD_ID = characterResourceInfo.RECORD_ID,
                    MONSTER_TYPE = characterResourceInfo.TYPE,
                    REAL_NAME = characterResourceInfo.REAL_NAME,
                    ZOKUSEI = ((int)characterResourceInfo._zokusei).ToString(),
                    SPECIAL_ZOKUSEI = characterResourceInfo.SPECIAL_ZOKUSEI,
                    BASIC_MOVEMENT_PACK = characterResourceInfo.BASIC_MOVEMENT_PACK
                };
                switch (characterResourceInfo.MoveType)
                {
                    case MoveType.Move_normal:
                        row.MOVE_TYPE = "Move1";
                        break;
                    case MoveType.Move_slow:
                        row.MOVE_TYPE = "Move2";
                        break;
                    case MoveType.Move_fast:
                        row.MOVE_TYPE = "Move3";
                        break;
                    default:
                        row.MOVE_TYPE = "Move1";
                        break;
                }
                switch (characterResourceInfo.RushType)
                {
                    case RushType.Jump:
                        row.DODGE_SKILL = "Jump";
                        break;
                    case RushType.Rush:
                        row.DODGE_SKILL = "Rush";
                        break;
                    case RushType.RushBack:
                        row.DODGE_SKILL = "RushBack";
                        break;
                    case RushType.None:
                        row.DODGE_SKILL = "None";
                        break;
                    default:
                        row.DODGE_SKILL = "RushBack";
                        break;
                }
                row.DEFENDABLE_FLAG = characterResourceInfo.DEFENDABLE_FLAG ? "1" : "0";

                row.RARITY_LEVEL = characterResourceInfo.RARITY_LEVEL.ToString();
                rowList.Add(row);
            }

            string[][] grid = new string[rowList.Count + 1][];
            for (int i = 0; i < grid.Length; i++)
            {
                grid[i] = new string[10];
                if (i == 0)
                {
                    grid[i][0] = "RECORD_ID";
                    grid[i][1] = "REAL_NAME";
                    grid[i][2] = "MONSTER_TYPE_CODE";
                    grid[i][3] = "ZOKUSEI";
                    grid[i][4] = "SPECIAL_ZOKUSEI";
                    grid[i][5] = "RARITY_LEVEL";
                    grid[i][6] = "BASIC_MOVEMENT_PACK";
                    grid[i][7] = "MOVE_TYPE";
                    grid[i][8] = "MOTILITY_SKILL_PACK";
                    grid[i][9] = "DEFENDABLE_FLAG";
                }
                else
                {
                    grid[i][0] = rowList[i - 1].RECORD_ID;
                    grid[i][1] = rowList[i - 1].REAL_NAME;
                    grid[i][2] = rowList[i - 1].MONSTER_TYPE;
                    grid[i][3] = rowList[i - 1].ZOKUSEI;
                    grid[i][4] = rowList[i - 1].SPECIAL_ZOKUSEI;
                    grid[i][5] = rowList[i - 1].RARITY_LEVEL;
                    grid[i][6] = rowList[i - 1].BASIC_MOVEMENT_PACK;
                    grid[i][7] = rowList[i - 1].MOVE_TYPE;
                    grid[i][8] = rowList[i - 1].DODGE_SKILL;
                    grid[i][9] = rowList[i - 1].DEFENDABLE_FLAG;
                }
            }
            string delimiter = ",";
            StringBuilder sb = new StringBuilder();

            for (int index = 0; index < grid.Length; index++)
            {
                sb.AppendLine(string.Join(delimiter, grid[index]));
            }
            
            Debug.Log("尝试最终保存文件" + filePath);
            StreamWriter outStream = File.CreateText(filePath);
            outStream.WriteLine(sb);
            outStream.Close();
        }
        catch (Exception E)
        {
            Debug.Log(E);
        }
    }

    public List<CharConfig> RowToCharacterResourceInfoList(List<Row> List)
    {
        List<CharConfig> ToReturn = new List<CharConfig>();
        foreach (Row row in List)
        {
            CharConfig _CharacterResourceInfo = RowToCharacterResourceInfo(row);
            if (_CharacterResourceInfo != null)
                ToReturn.Add(_CharacterResourceInfo);
            else
                Debug.Log("这地方感觉有一些逻辑问题");
        }
        return ToReturn;
    }

    public Row CharacterResourceInfoToRow(CharConfig characterResourceInfo)
    {
        if (characterResourceInfo == null)
            return null;
        Row row = new Row
        {
            RECORD_ID = characterResourceInfo.RECORD_ID,
            MONSTER_TYPE = characterResourceInfo.TYPE,
            REAL_NAME = characterResourceInfo.REAL_NAME,
            ZOKUSEI = ((int)characterResourceInfo._zokusei).ToString(),
            SPECIAL_ZOKUSEI = characterResourceInfo.SPECIAL_ZOKUSEI,
            BASIC_MOVEMENT_PACK = characterResourceInfo.BASIC_MOVEMENT_PACK
        };
        switch (characterResourceInfo.MoveType)
        {
            case MoveType.Move_normal:
                row.MOVE_TYPE = "Move1";
                break;
            case MoveType.Move_slow:
                row.MOVE_TYPE = "Move2";
                break;
            case MoveType.Move_fast:
                row.MOVE_TYPE = "Move3";
                break;
        }
        switch(characterResourceInfo.RushType)
        {
            case RushType.None:
                row.DODGE_SKILL = "None";
                break;
            case RushType.Jump:
                row.DODGE_SKILL = "Jump";
                break;
            case RushType.Rush:
                row.DODGE_SKILL = "Rush";
                break;
            case RushType.RushBack:
                row.DODGE_SKILL = "RushBack";
                break;
        }

        row.DEFENDABLE_FLAG = characterResourceInfo.DEFENDABLE_FLAG ? "1" : "0";
        row.RARITY_LEVEL = characterResourceInfo.RARITY_LEVEL.ToString();
        return row;
    }

    public CharConfig RowToCharacterResourceInfo(Row row)
    {
        if (row == null)
            return null;
        CharConfig _CharacterResourceInfo = new CharConfig
        {
            RECORD_ID = row.RECORD_ID,
            TYPE = row.MONSTER_TYPE,
            REAL_NAME = row.REAL_NAME
        };

        switch (row.ZOKUSEI)
        {
            case "4":
                _CharacterResourceInfo._zokusei = Zokusei.blueMagic;
                break;
            case "3":
                _CharacterResourceInfo._zokusei = Zokusei.redMagic;
                break;
            case "5":
                _CharacterResourceInfo._zokusei = Zokusei.greenMagic;
                break;
            case "1":
                _CharacterResourceInfo._zokusei = Zokusei.darkMagic;
                break;
            case "2":
                _CharacterResourceInfo._zokusei = Zokusei.lightMagic;
                break;
            default:
                _CharacterResourceInfo._zokusei = Zokusei.lightMagic;
                break;
        }

        _CharacterResourceInfo.BASIC_MOVEMENT_PACK = row.BASIC_MOVEMENT_PACK;

        switch (row.MOVE_TYPE)
        {
            case "Move1":
                _CharacterResourceInfo.MoveType = MoveType.Move_normal;
                break;
            case "Move2":
                _CharacterResourceInfo.MoveType = MoveType.Move_slow;
                break;
            case "Move3":
                _CharacterResourceInfo.MoveType = MoveType.Move_fast;
                break;
            default:
                _CharacterResourceInfo.MoveType = MoveType.Move_normal;
                break;
        }

        switch (row.DODGE_SKILL)
        {
            case "Jump":
                _CharacterResourceInfo.RushType = RushType.Jump;
                break;
            case "Rush":
                _CharacterResourceInfo.RushType = RushType.Rush;
                break;
            case "RushBack":
                _CharacterResourceInfo.RushType = RushType.RushBack;
                break;
            case "None":
                _CharacterResourceInfo.RushType = RushType.None;
                break;
            default:
                _CharacterResourceInfo.RushType = RushType.RushBack;
                break;
        }

        _CharacterResourceInfo.DEFENDABLE_FLAG = row.DEFENDABLE_FLAG == "1";
        _CharacterResourceInfo.RARITY_LEVEL = Int32.Parse(row.RARITY_LEVEL);
        return _CharacterResourceInfo;
    }

    public int NumRows()
	{
		return rowList.Count;
	}
   
    public static IDictionary<string,string> GetMonsterRecordIDsAndNamesArrayDic(string type)// close, near, far.rarelevel = -1代表全部，0代表无星级技能
    {
        IDictionary<string, string> Mdic = new Dictionary<string, string>();
        List<Row> references = Instance.FindAll_MONSTER_TYPE(type);
        foreach (Row one in references)
        {
            Mdic.Add(one.RECORD_ID,one.REAL_NAME);
        }
        return Mdic;
    }

    public List<Row> FindAll_TYPE_REALNAME(string MONSTER_TYPE, string keyName)
    {
        //monsterTypeReferenceTable.Row reference = monsterTypeReferenceTable.Instance.Find_MONSTER_TYPE_CODE(row.MONSTER_TYPE_CODE);
        return (rowList.FindAll(x => x.REAL_NAME == keyName).Intersect(rowList.FindAll(x => x.MONSTER_TYPE == MONSTER_TYPE))).ToList();
    }

    public Row GetAt(int i)
	{
        return rowList.Count <= i ? null : rowList[i];
    }

    public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
    public Row Find_REAL_NAME(string find)
	{
		return rowList.Find(x => x.REAL_NAME == find);
	}
    
    public List<Row> FindAll_MONSTER_TYPE(string find)
    {
        return rowList.FindAll(x => x.MONSTER_TYPE == find);
    }
    
	public Row Find_Zokusei(string find)
	{
		return rowList.Find(x => x.ZOKUSEI == find);
	}
	public List<Row> FindAll_Zokusei(string find)
	{
		return rowList.FindAll(x => x.ZOKUSEI == find);
	}
	public Row Find_personalMagicPack(string find)
	{
        return rowList.Find(x => x.SPECIAL_ZOKUSEI == find);
	}
	public List<Row> FindAll_personalMagicPack(string find)
	{
		return rowList.FindAll(x => x.SPECIAL_ZOKUSEI == find);
	}
	public Row Find_BasicMoveSet(string find)
	{
        return rowList.Find(x => x.BASIC_MOVEMENT_PACK == find);
	}
	public List<Row> FindAll_BasicMoveSet(string find)
	{
		return rowList.FindAll(x => x.BASIC_MOVEMENT_PACK == find);
	}
	public Row Find_MoveType(string find)
	{
        return rowList.Find(x => x.MOVE_TYPE == find);
	}
	public List<Row> FindAll_MoveType(string find)
	{
		return rowList.FindAll(x => x.MOVE_TYPE == find);
	}
	public Row Find_accSkill(string find)
	{
		return rowList.Find(x => x.DODGE_SKILL == find);
	}
	public List<Row> FindAll_accSkill(string find)
	{
		return rowList.FindAll(x => x.DODGE_SKILL == find);
	}
	public Row Find_canDefend(string find)
	{
        return rowList.Find(x => x.DEFENDABLE_FLAG == find);
	}
	public List<Row> FindAll_canDefend(string find)
	{
		return rowList.FindAll(x => x.DEFENDABLE_FLAG == find);
	}
	public Row Find_rarelevel(string find)
	{
		return rowList.Find(x => x.RARITY_LEVEL == find);
	}
	public List<Row> FindAll_rarelevel(string find)
	{
		return rowList.FindAll(x => x.RARITY_LEVEL == find);
	}
    
    // 20200322 新追加。角色type的追加按说不应该那么麻烦，事前定义好就可以
    public List<string> GetTypeList()
    {
        List<string> typeList = new List<string>
        {
            "human",
            "dog"
        };
        return typeList;
    }
}

