// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using System.Text;

public class monstersConfigTable
{
    [Serializable]
    public class Row
	{
		public string id;
		public string type;
        public string realName;
		public string zokusei;
		public string personalMagicPack;
		public string basicMoveSet;
		public string moveType;
		public string accSkill;
		public string canDefend;
		public string rarelevel;
	}

	public List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
        try
        {
            for (int i = 1; i < grid.Length; i++)
            {
                if (grid[i].Length == 10)
                {
                    Row row = new Row();
                    row.id = grid[i][0];
                    row.type = grid[i][1];
                    row.realName = grid[i][2];
                    row.zokusei = grid[i][3];
                    row.personalMagicPack = grid[i][4];
                    row.basicMoveSet = grid[i][5];
                    row.moveType = grid[i][6];
                    row.accSkill = grid[i][7];
                    row.canDefend = grid[i][8];
                    row.rarelevel = grid[i][9];
                    rowList.Add(row);
                }
            }
            isLoaded = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
    }

    public void SaveByCurrentRows(string filePath)
    {
        List<Row> toDeleteList = new List<Row>();
        foreach (Row row in rowList)
        {
            if (row.realName == null || row.id == null || row.id == "" || int.Parse(row.id) < 0)
                toDeleteList.Add(row);
        }
        foreach (Row row in toDeleteList)
        {
            Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
            rowList.Remove(row);
        }

        string[][] grid = new string[rowList.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[10];
            if (i == 0)
            {
                grid[i][0] = "id";
                grid[i][1] = "type";
                grid[i][2] = "realName";
                grid[i][3] = "zokusei";
                grid[i][4] = "personalMagicPack";
                grid[i][5] = "basicMoveSet";
                grid[i][6] = "moveType";
                grid[i][7] = "accSkill";
                grid[i][8] = "canDefend";
                grid[i][9] = "rarelevel";
            }
            else
            {
                grid[i][0] = rowList[i - 1].id;
                grid[i][1] = rowList[i - 1].type;
                grid[i][2] = rowList[i - 1].realName;
                grid[i][3] = rowList[i - 1].zokusei;
                grid[i][4] = rowList[i - 1].personalMagicPack;
                grid[i][5] = rowList[i - 1].basicMoveSet;
                grid[i][6] = rowList[i - 1].moveType;
                grid[i][7] = rowList[i - 1].accSkill;
                grid[i][8] = rowList[i - 1].canDefend;
                grid[i][9] = rowList[i - 1].rarelevel;
            }
        }
        string delimiter = ",";
        StringBuilder sb = new StringBuilder();

        for (int index = 0; index < grid.Length; index++)
            sb.AppendLine(string.Join(delimiter, grid[index]));

        Debug.Log("尝试最终保存文件" + filePath);
        StreamWriter outStream = System.IO.File.CreateText(filePath);
        outStream.WriteLine(sb);
        outStream.Close();
    }

    // by haku 9.12
    // filePath的后面记得包括文件名和CSV后缀？
    public void Save(string filePath, List<CharacterResourceInfo> characterResourceList)
    {
        try
        {
            rowList.Clear();

            foreach (CharacterResourceInfo characterResourceInfo in characterResourceList)
            {
                Debug.Log("尝试整理角色：" + characterResourceInfo.prefabName);
                Row row = new Row();
                row.id = characterResourceInfo.monsterId.ToString();
                row.type = characterResourceInfo.type;
                row.realName = characterResourceInfo.prefabName;

                switch (characterResourceInfo._zokusei)
                {
                    case zokusei.blueMagic:
                        row.zokusei = "blueMagic";
                        break;
                    case zokusei.redMagic:
                        row.zokusei = "redMagic";
                        break;
                    case zokusei.greenMagic:
                        row.zokusei = "greenMagic";
                        break;
                    case zokusei.darkMagic:
                        row.zokusei = "darkMagic";
                        break;
                    case zokusei.lightMagic:
                        row.zokusei = "lightMagic";
                        break;
                    default:
                        row.zokusei = "redMagic";
                        break;
                }

                row.personalMagicPack = characterResourceInfo.personalMagicPack;
                row.basicMoveSet = characterResourceInfo.BasicMoveSetName;
                switch(characterResourceInfo.moveType)
                {
                    case MoveType.Mode1:
                        row.moveType = "Move1";
                        break;
                    case MoveType.Mode2:
                        row.moveType = "Move2";
                        break;
                    case MoveType.Mode3:
                        row.moveType = "Move3";
                        break;
                    default:
                        row.moveType = "Move1";
                        break;
                }

                switch (characterResourceInfo.rushType)
                {
                    case RushType.Jump:
                        row.accSkill = "Jump";
                        break;
                    case RushType.Rush:
                        row.accSkill = "Rush";
                        break;
                    case RushType.RushBack:
                        row.accSkill = "RushBack";
                        break;
                    case RushType.None:
                        row.accSkill = "None";
                        break;
                    default:
                        row.accSkill = "RushBack";
                        break;
                }

                if (characterResourceInfo.canDefend)
                    row.canDefend = "1";
                else
                    row.canDefend = "0";

                row.rarelevel = characterResourceInfo.rarelevel.ToString();
                rowList.Add(row);
            }

            string[][] grid = new string[rowList.Count + 1][];
            for (int i = 0; i < grid.Length; i++)
            {
                grid[i] = new string[10];
                if (i == 0)
                {
                    grid[i][0] = "id";
                    grid[i][1] = "type";
                    grid[i][2] = "realName";
                    grid[i][3] = "zokusei";
                    grid[i][4] = "personalMagicPack";
                    grid[i][5] = "basicMoveSet";
                    grid[i][6] = "moveType";
                    grid[i][7] = "accSkill";
                    grid[i][8] = "canDefend";
                    grid[i][9] = "rarelevel";
                }
                else
                {
                    grid[i][0] = rowList[i - 1].id;
                    grid[i][1] = rowList[i - 1].type;
                    grid[i][2] = rowList[i - 1].realName;
                    grid[i][3] = rowList[i - 1].zokusei;
                    grid[i][4] = rowList[i - 1].personalMagicPack;
                    grid[i][5] = rowList[i - 1].basicMoveSet;
                    grid[i][6] = rowList[i - 1].moveType;
                    grid[i][7] = rowList[i - 1].accSkill;
                    grid[i][8] = rowList[i - 1].canDefend;
                    grid[i][9] = rowList[i - 1].rarelevel;
                }
            }
            string delimiter = ",";
            StringBuilder sb = new StringBuilder();

            for (int index = 0; index < grid.Length; index++)
                sb.AppendLine(string.Join(delimiter, grid[index]));

            Debug.Log("尝试最终保存文件" + filePath);
            StreamWriter outStream = System.IO.File.CreateText(filePath);
            outStream.WriteLine(sb);
            outStream.Close();
        }
        catch (Exception E)
        {
            Debug.Log(E);
        }
    }

    public List<CharacterResourceInfo> RowToCharacterResourceInfoList(List<Row> List)
    {
        List<CharacterResourceInfo> ToReturn = new List<CharacterResourceInfo>();
        foreach (Row row in List)
        {
            ToReturn.Add(RowToCharacterResourceInfo(row));
        }
        return ToReturn;
    }

    public Row CharacterResourceInfoToRow(CharacterResourceInfo characterResourceInfo)
    {
        if (characterResourceInfo == null)
            return null;
        Row row = new Row();
        row.id = characterResourceInfo.monsterId.ToString();

        row.type = characterResourceInfo.type.ToString();
        row.realName = characterResourceInfo.prefabName.ToString();
        switch (characterResourceInfo._zokusei)
        {
            case zokusei.blueMagic:
                row.zokusei = "blueMagic";
                break;
            case zokusei.redMagic:
                row.zokusei = "redMagic";
                break;
            case zokusei.greenMagic:
                row.zokusei = "greenMagic";
                break;
            case zokusei.darkMagic:
                row.zokusei = "darkMagic";
                break;
            case zokusei.lightMagic:
                row.zokusei = "lightMagic";
                break;
        }

        row.personalMagicPack = characterResourceInfo.personalMagicPack;
        row.basicMoveSet = characterResourceInfo.BasicMoveSetName;
        switch(characterResourceInfo.moveType)
        {
            case MoveType.Mode1:
                row.moveType = "Move1";
                break;
            case MoveType.Mode2:
                row.moveType = "Move2";
                break;
            case MoveType.Mode3:
                row.moveType = "Move3";
                break;
        }
        switch(characterResourceInfo.rushType)
        {
            case RushType.None:
                row.accSkill = "None";
                break;
            case RushType.Jump:
                row.accSkill = "Jump";
                break;
            case RushType.Rush:
                row.accSkill = "Rush";
                break;
            case RushType.RushBack:
                row.accSkill = "RushBack";
                break;
        }

        if (characterResourceInfo.canDefend)
            row.canDefend = "1";
        else
            row.canDefend = "0";

        row.rarelevel = characterResourceInfo.rarelevel.ToString();
        return row;
    }

    public CharacterResourceInfo RowToCharacterResourceInfo(Row row)
    {
        if (row == null)
            return null;
        CharacterResourceInfo _CharacterResourceInfo = new CharacterResourceInfo();
        _CharacterResourceInfo.monsterId = int.Parse(row.id);
        _CharacterResourceInfo.type = row.type;
        _CharacterResourceInfo.prefabName = row.realName;

        switch (row.zokusei)
        {
            case "blueMagic":
                _CharacterResourceInfo._zokusei = zokusei.blueMagic;
                break;
            case "redMagic":
                _CharacterResourceInfo._zokusei = zokusei.redMagic;
                break;
            case "greenMagic":
                _CharacterResourceInfo._zokusei = zokusei.greenMagic;
                break;
            case "darkMagic":
                _CharacterResourceInfo._zokusei = zokusei.darkMagic;
                break;
            case "lightMagic":
                _CharacterResourceInfo._zokusei = zokusei.lightMagic;
                break;
            default:
                _CharacterResourceInfo._zokusei = zokusei.redMagic;
                break;
        }

        _CharacterResourceInfo.BasicMoveSetName = row.basicMoveSet;

        switch (row.moveType)
        {
            case "Move1":
                _CharacterResourceInfo.moveType = MoveType.Mode1;
                break;
            case "Move2":
                _CharacterResourceInfo.moveType = MoveType.Mode2;
                break;
            case "Move3":
                _CharacterResourceInfo.moveType = MoveType.Mode3;
                break;
            case "Test":
                _CharacterResourceInfo.moveType = MoveType.Test;
                break;
            default:
                _CharacterResourceInfo.moveType = MoveType.Mode1;
                break;
        }

        switch (row.accSkill)
        {
            case "Jump":
                _CharacterResourceInfo.rushType = RushType.Jump;
                break;
            case "Rush":
                _CharacterResourceInfo.rushType = RushType.Rush;
                break;
            case "RushBack":
                _CharacterResourceInfo.rushType = RushType.RushBack;
                break;
            case "None":
                _CharacterResourceInfo.rushType = RushType.None;
                break;
            default:
                _CharacterResourceInfo.rushType = RushType.RushBack;
                break;
        }

        if (row.canDefend == "1")
            _CharacterResourceInfo.canDefend = true;
        else
            _CharacterResourceInfo.canDefend = false;

        _CharacterResourceInfo.rarelevel = Int32.Parse(row.rarelevel);
        return _CharacterResourceInfo;
    }

    public int NumRows()
	{
		return rowList.Count;
	}

    public List<string> getTypeList()
    {
        List<string> typeList = new List<string>();
        foreach (Row row in rowList)
        {
            if (!typeList.Contains(row.type))
            {
                typeList.Add(row.type);
            }
        }
        return typeList;
    }

    public List<string> getRealNameList()
    {
        List<string> List = new List<string>();
        foreach (Row row in rowList)
        {
            if (!List.Contains(row.realName))
            {
                List.Add(row.realName);
            }
        }
        return List;
    }

    public List<int> getIDList()
    {
        List<int> IDList = new List<int>();
        foreach (Row row in rowList)
        {
            if (!IDList.Contains(Int32.Parse(row.id)))
            {
                IDList.Add(Int32.Parse(row.id));
            }
        }
        return IDList;
    }

    public List<string> getRealNameList(string type)
    {
        List<string> List = new List<string>();
        foreach (Row row in rowList)
        {
            if (!List.Contains(row.realName) && type == row.type)
            {
                List.Add(row.realName);
            }
        }
        return List;
    }

    public List<int> getIDList(string type)
    {
        List<int> IDList = new List<int>();
        foreach (Row row in rowList)
        {
            if (!IDList.Contains(Int32.Parse(row.id)) && type == row.type)
            {
                IDList.Add(Int32.Parse(row.id));
            }
        }
        return IDList;
    }

    public List<Row> FindAll_type_realName(string type, string keyName)
    {
        return (rowList.FindAll(x => x.realName == keyName).Intersect(rowList.FindAll(x => x.type == type))).ToList();
    }

    public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_ID(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_ID(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}

    public Row Find_realName(string find)
	{
		return rowList.Find(x => x.realName == find);
	}
	public List<Row> FindAll_realName(string find)
	{
		return rowList.FindAll(x => x.realName == find);
	}
	public Row Find_Zokusei(string find)
	{
		return rowList.Find(x => x.zokusei == find);
	}
	public List<Row> FindAll_Zokusei(string find)
	{
		return rowList.FindAll(x => x.zokusei == find);
	}
	public Row Find_personalMagicPack(string find)
	{
        return rowList.Find(x => x.personalMagicPack == find);
	}
	public List<Row> FindAll_personalMagicPack(string find)
	{
		return rowList.FindAll(x => x.personalMagicPack == find);
	}
	public Row Find_BasicMoveSet(string find)
	{
        return rowList.Find(x => x.basicMoveSet == find);
	}
	public List<Row> FindAll_BasicMoveSet(string find)
	{
		return rowList.FindAll(x => x.basicMoveSet == find);
	}
	public Row Find_MoveType(string find)
	{
        return rowList.Find(x => x.moveType == find);
	}
	public List<Row> FindAll_MoveType(string find)
	{
		return rowList.FindAll(x => x.moveType == find);
	}
	public Row Find_accSkill(string find)
	{
		return rowList.Find(x => x.accSkill == find);
	}
	public List<Row> FindAll_accSkill(string find)
	{
		return rowList.FindAll(x => x.accSkill == find);
	}
	public Row Find_canDefend(string find)
	{
        return rowList.Find(x => x.canDefend == find);
	}
	public List<Row> FindAll_canDefend(string find)
	{
		return rowList.FindAll(x => x.canDefend == find);
	}
	public Row Find_rarelevel(string find)
	{
		return rowList.Find(x => x.rarelevel == find);
	}
	public List<Row> FindAll_rarelevel(string find)
	{
		return rowList.FindAll(x => x.rarelevel == find);
	}
}