// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using System.Text;

public class monstersConfigTable
{
    private static monstersConfigTable instance;
    public static monstersConfigTable Instance
    {
        get
        {
            if (instance == null)
                instance = new monstersConfigTable();
            return instance;
        }
    }
    public static IDictionary<string, CharacterResourceInfo> CharacterResourceInfoDic = new Dictionary<string, CharacterResourceInfo>();

    [Serializable]
    public class Row
	{
		public string RECORD_ID;
        public string REAL_NAME;
        public string MONSTER_TYPE;
		public string ZOKUSEI;
		public string SPECIAL_ZOKUSEI;
        public string RARITY_LEVEL;
		public string BASIC_MOVEMENT_PACK;
		public string MOVE_TYPE;
		public string MOTILITY_SKILL_PACK;
		public string DEFENDABLE_FLAG;
	}
            
    public static CharacterResourceInfo getCharacterResourceInfo(string resourceId)
    {
        return CharacterResourceInfoDic.ContainsKey(resourceId) ? CharacterResourceInfoDic[resourceId] : null;
    }
    public static void loadMonstersConfigByResource()
    {
        //暂时做如下处理
        TextAsset CSV = Resources.Load("Account/mst_monster") as TextAsset;
        if (CSV)
        {
            Instance.Load(CSV);
        }
        else
            Debug.Log("没能读取到角色数据库文件。");
    }
    
    public static void refreshCharacterResourceInfoDic()
    {
        CharacterResourceInfoDic.Clear();
        List<CharacterResourceInfo> characterResourceInfos = Instance.RowToCharacterResourceInfoList(Instance.rowList);
        foreach (CharacterResourceInfo one in characterResourceInfos)            
        {
            CharacterResourceInfoDic.Add(one.RECORD_ID,one);
        }
    }
    
    public IEnumerator loadMonstersConfig()
    {
        switch (ResourceLoadingSetting.Instance.ConfigFileLoadingMode)
        {
            case ResourceLoadMode.CachAB:
                break;
            case ResourceLoadMode.StreamingAssetAB:
                break;
            case ResourceLoadMode.Resource:
                loadMonstersConfigByResource();
                break;
        }
        refreshCharacterResourceInfoDic();
        yield break;    
    }

	public List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
        try
        {
            for (int i = 1; i < grid.Length; i++)
            {
                Row row = new Row();
                row.RECORD_ID = grid[i][0];
                row.REAL_NAME = grid[i][1];
                row.MONSTER_TYPE = grid[i][2];
                row.ZOKUSEI = grid[i][3];
                row.SPECIAL_ZOKUSEI = grid[i][4];
                row.RARITY_LEVEL = grid[i][5];
                row.BASIC_MOVEMENT_PACK = grid[i][6];
                row.MOVE_TYPE = grid[i][7];
                row.MOTILITY_SKILL_PACK = grid[i][8];
                row.DEFENDABLE_FLAG = grid[i][9];
                rowList.Add(row);
            }
            isLoaded = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
    }

    public void SaveByCurrentRows(string filePath)
    {
        List<Row> toDeleteList = new List<Row>();
        foreach (Row row in rowList)
        {
            if (row.REAL_NAME == null)
                toDeleteList.Add(row);
        }
        foreach (Row row in toDeleteList)
        {
            Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
            rowList.Remove(row);
        }

        string[][] grid = new string[rowList.Count + 1][];
        for (int i = 0; i < grid.Length; i++)
        {
            grid[i] = new string[10];
            if (i == 0)
            {                        
                grid[i][0] = "RECORD_ID";
                grid[i][1] = "REAL_NAME";
                grid[i][2] = "MONSTER_TYPE_CODE";
                grid[i][3] = "ZOKUSEI";
                grid[i][4] = "SPECIAL_ZOKUSEI";
                grid[i][5] = "RARITY_LEVEL";
                grid[i][6] = "BASIC_MOVEMENT_PACK";
                grid[i][7] = "MOVE_TYPE";
                grid[i][8] = "MOTILITY_SKILL_PACK";
                grid[i][9] = "DEFENDABLE_FLAG";
            }
            else
            {
                grid[i][0] = rowList[i - 1].RECORD_ID;
                grid[i][1] = rowList[i - 1].REAL_NAME;
                grid[i][2] = rowList[i - 1].MONSTER_TYPE;
                grid[i][3] = rowList[i - 1].ZOKUSEI;
                grid[i][4] = rowList[i - 1].SPECIAL_ZOKUSEI;
                grid[i][5] = rowList[i - 1].RARITY_LEVEL;
                grid[i][6] = rowList[i - 1].BASIC_MOVEMENT_PACK;
                grid[i][7] = rowList[i - 1].MOVE_TYPE;
                grid[i][8] = rowList[i - 1].MOTILITY_SKILL_PACK;
                grid[i][9] = rowList[i - 1].DEFENDABLE_FLAG;
            }
        }
        string delimiter = ",";
        StringBuilder sb = new StringBuilder();

        for (int index = 0; index < grid.Length; index++)
            sb.AppendLine(string.Join(delimiter, grid[index]));

        Debug.Log("尝试最终保存文件" + filePath);
        StreamWriter outStream = System.IO.File.CreateText(filePath);
        outStream.WriteLine(sb);
        outStream.Close();
    }

    // by haku 9.12
    // filePath的后面记得包括文件名和CSV后缀？
    public void Save(string filePath, List<CharacterResourceInfo> characterResourceList)
    {
        try
        {
            rowList.Clear();

            foreach (CharacterResourceInfo characterResourceInfo in characterResourceList)
            {
                Debug.Log("尝试整理角色：" + characterResourceInfo.REAL_NAME);
                Row row = new Row();
                row.RECORD_ID = characterResourceInfo.RECORD_ID;
                row.MONSTER_TYPE = characterResourceInfo.type;
                row.REAL_NAME = characterResourceInfo.REAL_NAME;
                row.ZOKUSEI = ((int)characterResourceInfo._zokusei).ToString();
                row.SPECIAL_ZOKUSEI = characterResourceInfo.SPECIAL_ZOKUSEI;
                row.BASIC_MOVEMENT_PACK = characterResourceInfo.BASIC_MOVEMENT_PACK;
                switch(characterResourceInfo.moveType)
                {
                    case MoveType.Mode1:
                        row.MOVE_TYPE = "Move1";
                        break;
                    case MoveType.Mode2:
                        row.MOVE_TYPE = "Move2";
                        break;
                    case MoveType.Mode3:
                        row.MOVE_TYPE = "Move3";
                        break;
                    default:
                        row.MOVE_TYPE = "Move1";
                        break;
                }
                switch (characterResourceInfo.rushType)
                {
                    case RushType.Jump:
                        row.MOTILITY_SKILL_PACK = "Jump";
                        break;
                    case RushType.Rush:
                        row.MOTILITY_SKILL_PACK = "Rush";
                        break;
                    case RushType.RushBack:
                        row.MOTILITY_SKILL_PACK = "RushBack";
                        break;
                    case RushType.None:
                        row.MOTILITY_SKILL_PACK = "None";
                        break;
                    default:
                        row.MOTILITY_SKILL_PACK = "RushBack";
                        break;
                }
                if (characterResourceInfo.DEFENDABLE_FLAG)
                    row.DEFENDABLE_FLAG = "1";
                else
                    row.DEFENDABLE_FLAG = "0";

                row.RARITY_LEVEL = characterResourceInfo.RARITY_LEVEL.ToString();
                rowList.Add(row);
            }

            string[][] grid = new string[rowList.Count + 1][];
            for (int i = 0; i < grid.Length; i++)
            {
                grid[i] = new string[10];
                if (i == 0)
                {
                    grid[i][0] = "RECORD_ID";
                    grid[i][1] = "REAL_NAME";
                    grid[i][2] = "MONSTER_TYPE_CODE";
                    grid[i][3] = "ZOKUSEI";
                    grid[i][4] = "SPECIAL_ZOKUSEI";
                    grid[i][5] = "RARITY_LEVEL";
                    grid[i][6] = "BASIC_MOVEMENT_PACK";
                    grid[i][7] = "MOVE_TYPE";
                    grid[i][8] = "MOTILITY_SKILL_PACK";
                    grid[i][9] = "DEFENDABLE_FLAG";
                }
                else
                {
                    grid[i][0] = rowList[i - 1].RECORD_ID;
                    grid[i][1] = rowList[i - 1].REAL_NAME;
                    grid[i][2] = rowList[i - 1].MONSTER_TYPE;
                    grid[i][3] = rowList[i - 1].ZOKUSEI;
                    grid[i][4] = rowList[i - 1].SPECIAL_ZOKUSEI;
                    grid[i][5] = rowList[i - 1].RARITY_LEVEL;
                    grid[i][6] = rowList[i - 1].BASIC_MOVEMENT_PACK;
                    grid[i][7] = rowList[i - 1].MOVE_TYPE;
                    grid[i][8] = rowList[i - 1].MOTILITY_SKILL_PACK;
                    grid[i][9] = rowList[i - 1].DEFENDABLE_FLAG;
                }
            }
            string delimiter = ",";
            StringBuilder sb = new StringBuilder();

            for (int index = 0; index < grid.Length; index++)
                sb.AppendLine(string.Join(delimiter, grid[index]));

            Debug.Log("尝试最终保存文件" + filePath);
            StreamWriter outStream = System.IO.File.CreateText(filePath);
            outStream.WriteLine(sb);
            outStream.Close();
        }
        catch (Exception E)
        {
            Debug.Log(E);
        }
    }

    public List<CharacterResourceInfo> RowToCharacterResourceInfoList(List<Row> List)
    {
        List<CharacterResourceInfo> ToReturn = new List<CharacterResourceInfo>();
        foreach (Row row in List)
        {
            CharacterResourceInfo _CharacterResourceInfo = RowToCharacterResourceInfo(row);
            if (_CharacterResourceInfo != null)
                ToReturn.Add(_CharacterResourceInfo);
            else
                Debug.Log("这地方感觉有一些逻辑问题");
        }
        return ToReturn;
    }

    public Row CharacterResourceInfoToRow(CharacterResourceInfo characterResourceInfo)
    {
        if (characterResourceInfo == null)
            return null;
        Row row = new Row();
        row.RECORD_ID = characterResourceInfo.RECORD_ID;
        row.MONSTER_TYPE = characterResourceInfo.type;
        row.REAL_NAME = characterResourceInfo.REAL_NAME;
        row.ZOKUSEI = ((int)characterResourceInfo._zokusei).ToString();
        row.SPECIAL_ZOKUSEI = characterResourceInfo.SPECIAL_ZOKUSEI;
        row.BASIC_MOVEMENT_PACK = characterResourceInfo.BASIC_MOVEMENT_PACK;
        switch(characterResourceInfo.moveType)
        {
            case MoveType.Mode1:
                row.MOVE_TYPE = "Move1";
                break;
            case MoveType.Mode2:
                row.MOVE_TYPE = "Move2";
                break;
            case MoveType.Mode3:
                row.MOVE_TYPE = "Move3";
                break;
        }
        switch(characterResourceInfo.rushType)
        {
            case RushType.None:
                row.MOTILITY_SKILL_PACK = "None";
                break;
            case RushType.Jump:
                row.MOTILITY_SKILL_PACK = "Jump";
                break;
            case RushType.Rush:
                row.MOTILITY_SKILL_PACK = "Rush";
                break;
            case RushType.RushBack:
                row.MOTILITY_SKILL_PACK = "RushBack";
                break;
        }

        if (characterResourceInfo.DEFENDABLE_FLAG)
            row.DEFENDABLE_FLAG = "1";
        else
            row.DEFENDABLE_FLAG = "0";

        row.RARITY_LEVEL = characterResourceInfo.RARITY_LEVEL.ToString();
        return row;
    }

    public CharacterResourceInfo RowToCharacterResourceInfo(Row row)
    {
        if (row == null)
            return null;
        CharacterResourceInfo _CharacterResourceInfo = new CharacterResourceInfo();
        _CharacterResourceInfo.RECORD_ID = row.RECORD_ID;
        _CharacterResourceInfo.type = row.MONSTER_TYPE;
        _CharacterResourceInfo.REAL_NAME = row.REAL_NAME;

        switch (row.ZOKUSEI)
        {
            case "4":
                _CharacterResourceInfo._zokusei = zokusei.blueMagic;
                break;
            case "3":
                _CharacterResourceInfo._zokusei = zokusei.redMagic;
                break;
            case "5":
                _CharacterResourceInfo._zokusei = zokusei.greenMagic;
                break;
            case "1":
                _CharacterResourceInfo._zokusei = zokusei.darkMagic;
                break;
            case "2":
                _CharacterResourceInfo._zokusei = zokusei.lightMagic;
                break;
            default:
                _CharacterResourceInfo._zokusei = zokusei.lightMagic;
                break;
        }

        _CharacterResourceInfo.BASIC_MOVEMENT_PACK = row.BASIC_MOVEMENT_PACK;

        switch (row.MOVE_TYPE)
        {
            case "Move1":
                _CharacterResourceInfo.moveType = MoveType.Mode1;
                break;
            case "Move2":
                _CharacterResourceInfo.moveType = MoveType.Mode2;
                break;
            case "Move3":
                _CharacterResourceInfo.moveType = MoveType.Mode3;
                break;
            case "Test":
                _CharacterResourceInfo.moveType = MoveType.Test;
                break;
            default:
                _CharacterResourceInfo.moveType = MoveType.Mode1;
                break;
        }

        switch (row.MOTILITY_SKILL_PACK)
        {
            case "Jump":
                _CharacterResourceInfo.rushType = RushType.Jump;
                break;
            case "Rush":
                _CharacterResourceInfo.rushType = RushType.Rush;
                break;
            case "RushBack":
                _CharacterResourceInfo.rushType = RushType.RushBack;
                break;
            case "None":
                _CharacterResourceInfo.rushType = RushType.None;
                break;
            default:
                _CharacterResourceInfo.rushType = RushType.RushBack;
                break;
        }

        if (row.DEFENDABLE_FLAG == "1")
            _CharacterResourceInfo.DEFENDABLE_FLAG = true;
        else
            _CharacterResourceInfo.DEFENDABLE_FLAG = false;

        _CharacterResourceInfo.RARITY_LEVEL = Int32.Parse(row.RARITY_LEVEL);
        return _CharacterResourceInfo;
    }

    public int NumRows()
	{
		return rowList.Count;
	}
   
    public static RecordIDsAndNames getMonsterRecordIDsAndNamesArray(string type)// close, near, far.rarelevel = -1代表全部，0代表无星级技能
    {
        List<Row> references = Instance.FindAll_MONSTER_TYPE(type);
        List<string> RecordIDs = new List<string>();
        List<string> RealNames = new List<string>();
        foreach (Row one in references)
        {
            RecordIDs.Add(one.RECORD_ID);
            RealNames.Add(one.REAL_NAME);
        }
        RecordIDs.Add("-1");
        RealNames.Add("null");
        RecordIDsAndNames _RecordIDsAndNames = new RecordIDsAndNames(RecordIDs.ToArray(), RealNames.ToArray());
        return _RecordIDsAndNames;
    }

    public List<Row> FindAll_TYPE_REALNAME(string MONSTER_TYPE, string keyName)
    {
        //monsterTypeReferenceTable.Row reference = monsterTypeReferenceTable.Instance.Find_MONSTER_TYPE_CODE(row.MONSTER_TYPE_CODE);
        return (rowList.FindAll(x => x.REAL_NAME == keyName).Intersect(rowList.FindAll(x => x.MONSTER_TYPE == MONSTER_TYPE))).ToList();
    }

    public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
    public Row Find_REAL_NAME(string find)
	{
		return rowList.Find(x => x.REAL_NAME == find);
	}
    
    public List<Row> FindAll_MONSTER_TYPE(string find)
    {
        return rowList.FindAll(x => x.MONSTER_TYPE == find);
    }
    
	public Row Find_Zokusei(string find)
	{
		return rowList.Find(x => x.ZOKUSEI == find);
	}
	public List<Row> FindAll_Zokusei(string find)
	{
		return rowList.FindAll(x => x.ZOKUSEI == find);
	}
	public Row Find_personalMagicPack(string find)
	{
        return rowList.Find(x => x.SPECIAL_ZOKUSEI == find);
	}
	public List<Row> FindAll_personalMagicPack(string find)
	{
		return rowList.FindAll(x => x.SPECIAL_ZOKUSEI == find);
	}
	public Row Find_BasicMoveSet(string find)
	{
        return rowList.Find(x => x.BASIC_MOVEMENT_PACK == find);
	}
	public List<Row> FindAll_BasicMoveSet(string find)
	{
		return rowList.FindAll(x => x.BASIC_MOVEMENT_PACK == find);
	}
	public Row Find_MoveType(string find)
	{
        return rowList.Find(x => x.MOVE_TYPE == find);
	}
	public List<Row> FindAll_MoveType(string find)
	{
		return rowList.FindAll(x => x.MOVE_TYPE == find);
	}
	public Row Find_accSkill(string find)
	{
		return rowList.Find(x => x.MOTILITY_SKILL_PACK == find);
	}
	public List<Row> FindAll_accSkill(string find)
	{
		return rowList.FindAll(x => x.MOTILITY_SKILL_PACK == find);
	}
	public Row Find_canDefend(string find)
	{
        return rowList.Find(x => x.DEFENDABLE_FLAG == find);
	}
	public List<Row> FindAll_canDefend(string find)
	{
		return rowList.FindAll(x => x.DEFENDABLE_FLAG == find);
	}
	public Row Find_rarelevel(string find)
	{
		return rowList.Find(x => x.RARITY_LEVEL == find);
	}
	public List<Row> FindAll_rarelevel(string find)
	{
		return rowList.FindAll(x => x.RARITY_LEVEL == find);
	}
    
    public List<string> getTypeList()
    {
        List<string> typeList = new List<string>();
        foreach (Row row in rowList)
        {
            if (!typeList.Contains(row.MONSTER_TYPE))
            {
                typeList.Add(row.MONSTER_TYPE);
            }
        }
        return typeList;
    }
}

