// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class monster_nameTable
{
	public class Row
	{
		public string RECORD_ID;
		public string MONSTER_ID;
		public string EN_NAME;
		public string JP_NAME;
		public string CN_NAME;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.RECORD_ID = grid[i][0];
			row.MONSTER_ID = grid[i][1];
			row.EN_NAME = grid[i][2];
			row.JP_NAME = grid[i][3];
			row.CN_NAME = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public List<Row> FindAll_RECORD_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
	public Row Find_MONSTER_ID(string find)
	{
		return rowList.Find(x => x.MONSTER_ID == find);
	}
	public List<Row> FindAll_MONSTER_ID(string find)
	{
		return rowList.FindAll(x => x.MONSTER_ID == find);
	}
	public Row Find_EN_NAME(string find)
	{
		return rowList.Find(x => x.EN_NAME == find);
	}
	public List<Row> FindAll_EN_NAME(string find)
	{
		return rowList.FindAll(x => x.EN_NAME == find);
	}
	public Row Find_JP_NAME(string find)
	{
		return rowList.Find(x => x.JP_NAME == find);
	}
	public List<Row> FindAll_JP_NAME(string find)
	{
		return rowList.FindAll(x => x.JP_NAME == find);
	}
	public Row Find_CN_NAME(string find)
	{
		return rowList.Find(x => x.CN_NAME == find);
	}
	public List<Row> FindAll_CN_NAME(string find)
	{
		return rowList.FindAll(x => x.CN_NAME == find);
	}

}