// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public static class LevelExpConfig
{
    public class Row
    {
        public string Level;
        public string Exp;
    }

    readonly static List<Row> rowList = new List<Row>();
    static IDictionary<int, int> Dic = new Dictionary<int, int>();
    
    public static int GetLevelExp(int level)
    {
        return Dic.ContainsKey(level) ? Dic[level] : -1;
    }

    public static int GetLevelSumExp(int level)
    {
        int sum = 0;
        for (int i = 1; i <= level; i++)
        {
            sum += GetLevelExp(i);
        }
        return sum;
    }
    
    public static void LoadLevelExpConfig()
    {
        TextAsset csv = Resources.Load("Account/LevelExpConfig") as TextAsset;
        if (csv != null)
        {
            Load(csv);
        }
    }
    
	public static void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
            Row row = new Row
            {
                Level = grid[i][0],
                Exp = grid[i][1]
            };

            rowList.Add(row);
            if (!Dic.ContainsKey(int.Parse(row.Level)))
            {
                Dic.Add(int.Parse(row.Level), int.Parse(row.Exp));
            }else{
                Debug.Log("技能石等级经验对应表错误");
            }
        }
	}
    
    public static Current GetCurrentInfo(int exp)
    {
        int currentLevel = 1;
        while (Dic.ContainsKey(currentLevel) && Dic.ContainsKey(currentLevel + 1) && exp >= GetLevelSumExp(currentLevel) &&  exp >= GetLevelSumExp(currentLevel + 1))
        {
            currentLevel++;
        }
        Current Current = new Current
        {
            currentLevel = currentLevel,
            expRemain = exp - GetLevelSumExp(currentLevel),
            expToNextLevel = Dic.ContainsKey(currentLevel + 1) ? GetLevelSumExp(currentLevel + 1) - exp : 0
        };
        return Current;
    }
        
    public struct Current
    {
        public int currentLevel;
        public int expRemain;
        public int expToNextLevel;
    }
}