// This code automatically generated by TableCodeGen
using System;
using UnityEngine;
using PlayFab.ClientModels;
using System.Collections.Generic;

public class ArenaDummiesTable
{
	public class Row
	{
		public string NICK_NAME;
		public string ARENA_POINT;
		public string LEVEL;
		private FightMembers fightMembers;

		public void SetFightMembers(FightMembers f)
		{
			fightMembers = f;
			foreach (var member in fightMembers.EnemySets._SerializableSets)
			{
				member.value.level = Int32.Parse(LEVEL);
			}
		}
		
		public FightMembers GetFightMembers() => fightMembers;
	}

	readonly List<Row> rowList = new List<Row>();
	bool isLoaded = false;
	
	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load()
	{
		var csv = Resources.Load("Account/ArenaDummies") as TextAsset;
		Load(csv);
	}
	
	void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			var row = new Row
			{
				NICK_NAME = grid[i][0],
				ARENA_POINT = grid[i][1],
				LEVEL = grid[i][2]
			};

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}
	
	LeaderboardInfo RowToLeaderboardInfo(Row row)
	{
		var info = new LeaderboardInfo()
		{
			PlayerLeaderboardEntry = new PlayerLeaderboardEntry
			{
				DisplayName = row.NICK_NAME,
				StatValue = Int32.Parse(row.ARENA_POINT),
				Position =  -1
			},
			Team = row.GetFightMembers().EnemySets._SerializableSets
		};
		return info;
	}

	public List<LeaderboardInfo> GetDummiesAroundPoint(int point)
	{
		Row startRow = null;
		int startIndex;
		for (startIndex = 0 ; startIndex < rowList.Count; startIndex++)
		{
			var row = rowList[startIndex];
			if (Int32.Parse(row.ARENA_POINT) > point)
			{
				startRow = row;
				break;
			}
		}
		
		if (startRow == null)
			return new List<LeaderboardInfo>();
		
		var s = Resources.Load( "ArenaDummies/" + startRow.NICK_NAME) as FightInfo;
		if (s == null)
		{
			Debug.Log("Cant find dummy:"+ startRow.NICK_NAME);
			return new List<LeaderboardInfo>();
		}
		
		startRow.SetFightMembers(s.FightMembers);
		
		var returnValue = new List<LeaderboardInfo> { RowToLeaderboardInfo(startRow) };
		for (var i = startIndex + 1; i < startIndex + 3; i++)
		{
			if (i >= rowList.Count)
			{
				Debug.Log("No enough dummies?");
				break;
			}
			var row = rowList[i];
			var file = Resources.Load("ArenaDummies/" + row.NICK_NAME) as FightInfo;
			if (file == null)
			{
				Debug.Log("Cant find dummy:"+ startRow.NICK_NAME);
				continue;
			}
			row.SetFightMembers(file.FightMembers);
			returnValue.Add(RowToLeaderboardInfo(row));
		}
		return returnValue;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_NICK_NAME(string find)
	{
		return rowList.Find(x => x.NICK_NAME == find);
	}
	public List<Row> FindAll_NICK_NAME(string find)
	{
		return rowList.FindAll(x => x.NICK_NAME == find);
	}
	public Row Find_ARENA_POINT(string find)
	{
		return rowList.Find(x => x.ARENA_POINT == find);
	}
	public List<Row> FindAll_ARENA_POINT(string find)
	{
		return rowList.FindAll(x => x.ARENA_POINT == find);
	}
	public Row Find_LEVEL(string find)
	{
		return rowList.Find(x => x.LEVEL == find);
	}
	public List<Row> FindAll_LEVEL(string find)
	{
		return rowList.FindAll(x => x.LEVEL == find);
	}

}