// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class ArenaDummiesTable
{
	public class Row
	{
		public string NICK_NAME;
		public string ARENA_POINT;
		public string LEVEL;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.NICK_NAME = grid[i][0];
			row.ARENA_POINT = grid[i][1];
			row.LEVEL = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_NICK_NAME(string find)
	{
		return rowList.Find(x => x.NICK_NAME == find);
	}
	public List<Row> FindAll_NICK_NAME(string find)
	{
		return rowList.FindAll(x => x.NICK_NAME == find);
	}
	public Row Find_ARENA_POINT(string find)
	{
		return rowList.Find(x => x.ARENA_POINT == find);
	}
	public List<Row> FindAll_ARENA_POINT(string find)
	{
		return rowList.FindAll(x => x.ARENA_POINT == find);
	}
	public Row Find_LEVEL(string find)
	{
		return rowList.Find(x => x.LEVEL == find);
	}
	public List<Row> FindAll_LEVEL(string find)
	{
		return rowList.FindAll(x => x.LEVEL == find);
	}

}